### ISSUE TITLE
cannot access from china

### ISSUE THREAD

**Issue by jcouyang** [clojure/clojure-site#10]
I'm not sure where clojure.org is hosted, but it's currently block from china
```
 <<>> DiG 9.8.3-P1 <<>> clojure.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59644
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;clojure.org.			IN	A

;; ANSWER SECTION:
clojure.org.		3599	IN	A	75.126.104.177

;; Query time: 133 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Nov 16 11:58:01 2015
;; MSG SIZE  rcvd: 45
```
can I suggest if it's a static site, would it be better if just host on gh-pages?

**Comment by puredanger** [comment]
Currently clojure.org is hosted on wikispaces.com. This repo is the content that will be hosted on a new static site version once we go live with it.
