### ISSUE TITLE
http://clojure.org/about/spec listed twice

### ISSUE THREAD

**Issue by beatngu13** [clojure/clojure-site#100]
Section "spec" under http://clojure.org/about is listed twice if something under "FEATURES" or "OTHER HOSTS" is selected.

<img width="1552" alt="spec" src="https://cloud.githubusercontent.com/assets/11643714/15483704/5ad9ba22-2136-11e6-9992-f7bd6f53fe91.png">

**Comment by puredanger** [comment]
Thanks! This has been fixed already, but you may be seeing a cached version.
