### ISSUE TITLE
Protocols page is missing

### ISSUE THREAD

**Issue by ertugrulcetin** [clojure/clojure-site#101]
Page returns 404 error page.
I couldn't read the Protocols.

**Comment by puredanger** [comment]
The correct page is http://clojure.org/reference/protocols.

Did you follow a link from somewhere that had it listed otherwise?

**Comment by ertugrulcetin** [comment]
This was the link I guess (http://clojure.org/reference/protocols)
Now it's working (I was sure that it wasn't working 2 hours ago), I don't understand how...

**Comment by puredanger** [comment]
Ok, well good!
