### ISSUE TITLE
in reference/other_functions, "*out*" needs proper markup

### ISSUE THREAD

**Issue by uvtc** [clojure/clojure-site#114]
In reference/other_functions (the Printing section), it appears that the \*'s in "\*out\*" are being interpreted as markup for emphasis, and are not being rendered in the final output.

In markdown, I'd write "\*out\*" as `` `*out*` ``.

**Comment by puredanger** [comment]
I've fixed this for the next deploy, thanks!

**Comment by uvtc** [comment]
You're welcome. :+1:
