### ISSUE TITLE
reference/data_structures `(class 3.1M)` is not  clojure.lang.BigDecimal

### ISSUE THREAD

**Issue by uvtc** [clojure/clojure-site#115]
In reference/data_structures, it says

    (class 3.14159265358M)  ;=> clojure.lang.BigDecimal

but I get:

    (class 3.14159265358M) ;=> java.math.BigDecimal

**Comment by puredanger** [comment]
Yep, thanks. I've fixed it for the next deploy.

**Comment by uvtc** [comment]
:+1:
