### ISSUE TITLE
Add section header links to enable linking to specific sections

### ISSUE THREAD

**Issue by danielcompton** [clojure/clojure-site#117]
It would be helpful if there was a way to easily get a link to any section of content in the docs, to share specific sections. On GitHub (as an example), hovering over a header shows a link icon which is clickable to get a link to that header.

<img width="326" alt="screenshot of safari technology preview 15-06-16 9-38-04 am" src="https://cloud.githubusercontent.com/assets/811954/16060628/ddebda1e-32dc-11e6-820c-c4f64fc54cf9.png">

**Comment by puredanger** [comment]
Yeah, I have wanted this as well.

**Comment by puredanger** [comment]
Sorry, I did this a while back but didn't realize it was an issue here.
