### ISSUE TITLE
Clojure news on the home page

### ISSUE THREAD

**Issue by mzavarella30** [clojure/clojure-site#12]
I think it would be nice to have a small 'Clojure News & Updates' section on the front page, maybe towards the bottom. It would be a nice clean way for veteran users to stay up to date as well as a way for new users to see up front (literally) that keeping the Clojure community involved is a key priority. Some articles about releases, new tools, Clojure success stories, and so on, I think, would be a nice feature to have.

Anyone else?

**Comment by puredanger** [comment]
This is already in the design (not visible yet in the current repo).
