### ISSUE TITLE
Generator example in spec guide has bug and non-idiomatic usage of randomness

### ISSUE THREAD

**Issue by bhb** [clojure/clojure-site#130]
First of all, the [spec guide](http://clojure.org/guides/spec) is excellent. Thanks very much for all the detailed and useful content. 

I have noticed two issues in the section on [Custom Generators](http://clojure.org/guides/spec#_custom_generators)

Clojure version: 1.9.0-alpha10

#### `gen/string-alphanumeric` is a generator, but it is called like a function.

Repro:

1. Execute 
```clojure
(s/def ::hello
  (s/with-gen #(clojure.string/includes? % "hello")
    (fn [] (gen/fmap (fn [s] (let [i (rand-int (count s))]
                               (str (subs s 0 i) "hello" (subs s i))))
             (gen/string-alphanumeric)))))
(gen/sample (s/gen ::hello))
```

Expected: No error and example values are generated
Actual: `clojure.test.check.generators.Generator cannot be cast to clojure.lang.IFn`

#### Using a random value in a generator prevents shrinking

In the example, the call to `fmap` uses `rand-int`. I believe this is not a best practice, since random values can prevent shrinking. For example:

```clojure
;; this test will not shrink to a minimal, 2-character value
(defspec
  non-shrinking-test
  100
  (prop/for-all
   [s (gen/fmap (fn [s] (let [i (rand-int 10)]
                          (clojure.string/join (repeat i s))))
                gen/string-alphanumeric)]
   (< (count s) 2)))

;; this test will always shrink to the a minimal, 2-character value like "00"
(defspec
  shrinking-test
  100
  (prop/for-all
   [s (->> (gen/tuple gen/string-alphanumeric (gen/large-integer* {:min 0 :max 10}))
      (gen/fmap (fn [[s i]] (clojure.string/join (repeat i s))))
     )]
   (< (count s) 2)))
```

Granted, my example is contrived. However, I can envision programmers who are new to test.check creating hard-to-understand shrinking problems by using random values - and this example encourages this practice by calling it a "common trick".

I understand that using `gen/larger-integer*` will complicate this example (I think you'll need some combo of `gen/bind` and `gen/fmap`, but IMHO, it's better to avoid random values nonetheless.

**Comment by puredanger** [comment]
Thanks for the detailed report - I suspect you are right on all counts and will get those taken care of.

**Comment by puredanger** [comment]
On the first case here, the example is correct as given. Note that `gen` here is an alias for `clojure.spec.gen`, which wraps generators in 0-arg functions. The error you're reporting seems to be what would happen if gen was mapped to clojure.test.check.generators.

**Comment by bhb** [comment]
> The error you're reporting seems to be what would happen if gen was mapped to clojure.test.check.generators.

Ah, my mistake. Thanks for the explanation!
