### ISSUE TITLE
Guide to 'common' functional programming tools

### ISSUE THREAD

**Issue by admay** [clojure/clojure-site#131]
I'm just kind of just throwing this out there, but how about a guide to FP tools in Clojure.

Maybe something like,
1. Higher order functions & how to use them
2. Using HOFs with Filter
3. Map, Apply, Reduce, and how to use them

Nothing too in depth. More of an intro guide. But I've come across a lot of OO peeps who are looking to move to FP but struggle with the idea of HOFs and the 'common' FP tools.

I have a small outline that I can beef up for this.

**Comment by puredanger** [comment]
sure
