### ISSUE TITLE
link here from clojure.org?

### ISSUE THREAD

**Issue by johnv02139** [clojure/clojure-site#133]
I had a hard time finding this project.  I had to go to the Google group, and search for clojure.org, to find the announcement.  I would think, at least in the [contributing](http://clojure.org/community/contributing) section, there should be a link here.

**Comment by puredanger** [comment]
Thanks for the issue. I've added a link from the http://clojure.org/about/clojurescript page at least as a starting point. I'm going to look at other better places to do more before closing.

**Comment by htmfilho** [comment]
I've found the link to this repository (https://clojure.org/community/contributing_site) in clojure.org's website without major effort. But I think it would be more effective if the link above is also present in the footer section, as indicated in the screenshot below.

![clojure-org](https://cloud.githubusercontent.com/assets/200272/22503335/8ed99b3c-e871-11e6-9a3a-8ea35b03befe.png)

A new link in the red line pointing to https://clojure.org/community/contributing_site would be great.

If you agree I can do it.

**Comment by htmfilho** [comment]
Yes, indeed. :-)

**Comment by puredanger** [comment]
There is now a link in the footer for every content page (bottom right corner) to the page on the clojure site.
