### ISSUE TITLE
Add Clojure Remote 2017 event

### ISSUE THREAD

**Issue by rkneufeld** [clojure/clojure-site#155]
Hi folks,

I'd like to propose adding an event page for Clojure Remote 2017. I've already prepared [a branch](https://github.com/clojureremote/clojure-site/blob/add-clojureremote-event/content/events/2017/clojureremote.adoc) with the proposed page and can submit a PR if you are amenable to the page.

Cheers,
-Ryan

**Comment by puredanger** [comment]
Do it!
