### ISSUE TITLE
Redirect to HTTPS by default?

### ISSUE THREAD

**Issue by timmc** [clojure/clojure-site#159]
I'm really happy that clojure.org now supports HTTPS! Now that that's been true for a while, can you also go ahead and redirect to the TLS side of the site by default? And possibly add the Strict-Transport-Security header (HSTS) as well.

(As [noted](https://events.ccc.de/congress/2014/Fahrplan/system/attachments/2575/original/2014CCCReproducible.pdf) by developers on the Reproducible Builds team of the Debian and Tor projects, developers are an attractive target for state and other attackers, since compromising a developer can allow compromising all their software's users.)

**Comment by puredanger** [comment]
I've updated the AWS cloudfront distributions for clojure.org and clojurescript.org to redirect from http to https and that update is in the process of updating now (takes about 10 minutes usually).

AFAICT, AWS Cloudfront does not currently support HSTS so not much I can do about that one at the current time.

**Comment by puredanger** [comment]
And just as an aside if you're curious, we were serving about 1/3 of the total traffic on these sites via https prior.

**Comment by puredanger** [comment]
I've also switched many of the external links leaving the site from http to https (in particular download, github, clojure.org, and clojurescript.org links).

**Comment by timmc** [comment]
Ah, fantastic! Thank you. :-)

**Comment by puredanger** [comment]
Closing this for now. I'll keep an eye on whether we can add headers with Cloudfront going forward.
