### ISSUE TITLE
destructuring guide: "keyword-arg parsing"

### ISSUE THREAD

**Issue by uvtc** [clojure/clojure-site#160]
There's a terse portion in <https://clojure.org/guides/destructuring#_associative_destructuring> (starting with "`(def options '(:debug true))`") that left me confused.

I asked about it in the mailing list, and it was pointed out to me what it is. I recalled (after the explanation) that it's the same thing as described in the "Clojure Programming" book (p. 35); that is, "destructuring rest sequences as map key/value pairs".

This seems like a bit of magic to me, and is apparently an older-style though still supported destructuring technique. If it's to remain in the guide, it should have more explanation, including

  * that it's a special case of (associative) destructuring,
  * why it exists,
  * possibly what it's equivalent to (that is, what it saves you from otherwise having to type), and
  * how it only works with a rest seq (not just any vector).

Otherwise, I think it will only confuse readers if left as it is.

**Comment by uvtc** [comment]
Nice!

Though, I see a typo: your first example defn configure is missing `options` in the let binding.

Incidentally, for symmetry with the example that comes after, maybe you meant to write it like:

    (defn config [val {:keys [debug verbose] :or {debug false verbose false}}] ...)

?

**Comment by puredanger** [comment]
Thanks, fixed the typo. I pulled things out more to make it a little clearer that you were receiving a map there, so that was intentional.
