### ISSUE TITLE
Migrate the content in Confluence to clojure-site?

### ISSUE THREAD

**Issue by htmfilho** [clojure/clojure-site#163]
I've noticed that some content on the website is published on Confluence: 

http://dev.clojure.org/display/community/Clojure+User+Groups

Why not migrating this content to clojure-site?

**Comment by puredanger** [comment]
No one has gotten around to it - happy to have it there.

**Comment by puredanger** [comment]
Not everything makes sense to move but the user groups page would be a good candidate. I plan to move all the pages about contributing eventually but I'd prefer to move that area over as it needs some re-work and editing.

**Comment by puredanger** [comment]
I've moved many of the things of interest, still working some remainders under #327. Closing this one though. Re the original question, https://clojure.org/community/user_groups is the user groups list now.
