### ISSUE TITLE
Formatting issue on datatypes page

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-site#165]
On the datatypes page (https://clojure.org/reference/datatypes#_java_annotation_support), the meta for Bar is formatted as meta but then switches back to non-meta styling after the "}". 

Seems to be an issue in highlight.js (https://github.com/isagalaev/highlight.js/blob/master/src/languages/clojure.js). 

If anyone wants to submit a fix there, I'm happy to pull the latest for the site.

**Comment by maacl** [comment]
So I have created a small patch which produces this result:

![clj-hilightjs-patch](https://cloud.githubusercontent.com/assets/64092/26392349/91293490-4066-11e7-95dc-07a53fbc3776.png)

I personally like the highlighting within the annotation, as opposed to the all grey comment approach, especially for big annotations like in the example. Thoughts?

**Comment by puredanger** [comment]
Looks great to me. I'd prefer that this patch get applied to highlight.js and then I'd be happy to pull that down to the site.

**Comment by maacl** [comment]
Will do. Just wanted to check it looked reasonable to others. Will let you know when/if highlight.js merges the change.

**Comment by maacl** [comment]
Patch has been merged into master branch of highlight.js.

**Comment by puredanger** [comment]
Great! I will take a look at including it when I get a chance.

**Comment by maacl** [comment]
Just a friendly reminder that master branch of highlight.js has a fix for this.

**Comment by puredanger** [comment]
Thanks, updated.
