### ISSUE TITLE
Restore lost prominence of Google Group

### ISSUE THREAD

**Issue by pbwolf** [clojure/clojure-site#177]
The Google Group recently got significantly less prominent on clojure.org.  It used to be on the page that opened when you chose the major section "Community".  

In light of how the new initial Community page also has a really strong and clear entry, "Success Stories", on the menu that the desktop view shows, I suggest restoring "Community Resources" as the initial page for "Community".  By contrast, the email group's current menu entry, "Resources", is vague and less beckoning.

Furthermore, if you are on a mobile device, and you do not perceive any choice other than the default "Community" page whatever it is, then "Community Resources" is what you urgently need, not "Success Stories".  (You can ask the Google Group where the Success Stories are.)

**Comment by puredanger** [comment]
No plans to change the top nav right now - we'll continue to assess the priority of the various pages as time goes on.

Note that the home page still has a big callout on it "Community - We have a vibrant, flourishing community. Join us on our Google Group, find us on IRC in #clojure, or join our Slack channel." that is a giant link directly to the community resources page. This is also in the more abbreviated footer links.

I've pushed a change to the left nav "Resources" -> "Community Resources" - that seems reasonable.

Open to other ideas as well, but this is all I'm going to do with this issue atm.
