### ISSUE TITLE
Create guide to Clojure symbols

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-site#181]
Many people find https://yobriefca.se/blog/2014/05/19/the-weird-and-wonderful-characters-of-clojure/ to be a useful entry point to reading Clojure code or answering questions that are hard to search for, but it's currently a little out of date. It would be great to have something like this as a guide that would be a companion for the reference reader page.

It would be good to either get the author's permission to start from that post or to start with a clean rewrite with the same idea.

**Comment by slipset** [comment]
@kouphax is the original author.

**Comment by kouphax** [comment]
Hello All,

The road to hell is paved with good intentions... I had every notion to actually spin this out into it's own site (or add to an existing Clojure specific site) but sadly that never materialised due to other commitments.

If you want to use any of that article you have my full permission to do whatever you want to it.

**Comment by slipset** [comment]
I'd be happy transcribing the thing to adoc if that's any help.
I'd need some pointers to what needs to be changed, @puredanger , but maybe we could do that in the PR?

**Comment by slipset** [comment]
in progress: https://github.com/slipset/clojure-site/tree/characters_of_clojure

**Comment by puredanger** [comment]
Thanks @kouphax ! 

@slipset it's mostly things that need to be added: 

- `#?` and `#?@` for reader conditionals
- `#:` and `#::` for namespace map syntax (1.9+)
- `::` - should be "autoresolved keyword", not "qualified keyword" - the http://clojure.org/reference/reader page now has some info
- `#=` for reader eval could be added, although a) it's not officially supported and b) you'll rarely see it in actual code
- `%` should also have the symbol for variadic arguments - `%&`
- a lot of the headers say "blah blah macro" which might be confusing - "reader macro" would be better

**Comment by jafingerhut** [comment]
@kouphax If you have a chance, and can check the Clojure cheat sheet [1] to see if it is as complete as the article, after adding the things in @puredanger's list, and can at least mention which things you found missing in the cheat sheet here, or in an issue for the source at [2], I can see that they get added to that cheat sheet as well.  That, and I can change the link from the original "weird and wonderful characters" article to your new one.

[1] https://clojure.org/api/cheatsheet  (the "Special Character" section near the bottom left)
[2] https://github.com/jafingerhut/clojure-cheatsheets

**Comment by puredanger** [comment]
Live now at https://clojure.org/guides/weird_characters

**Comment by jafingerhut** [comment]
Looks nice!

I went through the Clojure Cheatsheet "Special Characters" section, and the list of characters in this new page, and the only differences in what is included that I found were:

+ the cheatsheet includes backslash \ for character literals, which seems worth adding to the new page, too
+ The new page mentions the core.async macros, but the cheatsheet does not.  I will add those to the cheatsheet soon-ish.
+ The new page mentions the namespaced map #: #:: syntax, but the cheatsheet does not.  I expect to add those to the cheatsheet at least by the time that Clojure 1.9 is released, if not sooner.
+ The new page mentions the #= sequence.  I don't think I will add this to the cheatsheet, given the rarity of its use and that it isn't officially supported.

**Comment by puredanger** [comment]
Thanks Andy!

**Comment by jafingerhut** [comment]
I have just published v38 of the Clojure cheat sheet in the usual place [1], with the core.async channel macros added to the Special Characters section, and with a link to this new guide at clojure.org.  It no longer links to the blog article that this addition to clojure.org was based upon.

[1] http://jafingerhut.github.io

**Comment by puredanger** [comment]
I have updated the Clojure site version of the cheatsheet to v38.

Going to close this issue now since the guide is out - if anyone has more stuff, file new issues or PRs.
