### ISSUE TITLE
Destructuring guide

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-site#19]

**Comment by mzavarella30** [comment]
This (guide)[https://www.youtube.com/watch?v=R-_uNvM6gpE] is the reason why I understand destructuring, if there is an 'outside resources' portion of the page, it's a really nice guide.

**Comment by slipset** [comment]
http://blog.jayfields.com/2010/07/clojure-destructuring.html 
is rather nice as well

**Comment by puredanger** [comment]
@mzavarella30 I'd like to have something written for the site, but it could also point to outside things at the end

**Comment by mzavarella30** [comment]
@puredanger I started writing a _very_ rough draft of a destructuring guide [here](https://github.com/mzavarella30/writings-and-such/blob/master/destructuring/destructuring.md) if you would like to check it out. I'm not much of a writer but it could serve as a foundation if there isn't one yet.

**Comment by puredanger** [comment]
I'd be happy to work on improving a submission - it should be in asciidoc though, not markdown.

**Comment by slipset** [comment]
It would be nice if the guide also mentioned all the places where you can use destructuring

- let-bindings
- for loops
- doseq
- etc

Also, if there are certain idioms that we use all the time, although I cannot think of any off the top of my head, that would be nice to include.

These are of course only suggestions.

**Comment by mzavarella30** [comment]
@puredanger, just converted the doc to asciidoc.

@slipset, I was thinking of added a "where to use it" section at the end. I'll look into the idioms and sort of 'best practices' and be sure to follow (and encourage the use) of them throughout the guide!

**Comment by pjlegato** [comment]
I've found this "Destructuring cheatsheet" useful: http://blog.brunobonacci.com/2014/11/16/clojure-complete-guide-to-destructuring/

**Comment by slipset** [comment]
https://reshmeeauckloo.wordpress.com/2015/12/09/clojure-destructuring/

**Comment by mzavarella30** [comment]
Now I'm confused, are we using vector/map destructuring or sequential/associative destructuring?

**Comment by reshmee011** [comment]
Associative destructuring refers to map and other associative data structures ( ,i.e. any data structure maintaining key /value pairs like set and vector)  destructuring.

Sequential destructuring refers to sequential collections (list,vector)  destructuring.

**Comment by mzavarella30** [comment]
I'll take that as we're going with associative and sequential destructuring. 

If any one wants to check out the [guide I've been writing](https://github.com/mzavarella30/writings-and-such/blob/master/destructuring/destructuring.adoc), that'd be awesome. It's still a little rough since I'm just trying to get all the information down that I can, but any constructive criticism would be great!

**Comment by mzavarella30** [comment]
Sorry about the lack of activity on this, I'm still working on it I've just been hung up at work lately.

**Comment by puredanger** [comment]
merged
