### ISSUE TITLE
Add spec questions to FAQ guide

### ISSUE THREAD

**Issue by danielcompton** [clojure/clojure-site#191]
There are a bunch of questions that come up often on the mailing list, Slack, e.t.c. It could be good to add an FAQ section to the spec guide that answers these questions. A few that I can think of:

- How do I write a spec for a map that only allows some keys?
- Can I add documentation for specs?
- Why does spec do x? (for many values of x)

**Comment by puredanger** [comment]
Changed title - would like to add these as a new section on https://clojure.org/guides/faq

**Comment by puredanger** [comment]
Over time I have added a bunch of these to https://clojure.org/guides/faq#_spec. At this point, going to close and will continue adding things as they come up.
