### ISSUE TITLE
Clarify Runtime Behavior of `in-ns` and `*ns*`

### ISSUE THREAD

**Issue by Artiavis** [clojure/clojure-site#192]
As an extension/copy of the conversation [on the mailing list](https://groups.google.com/forum/#!topic/clojure/6CXUNuPIUyQ):

The current docs on Namespaces at https://clojure.org/reference/namespaces accurately describe the characteristics and primality of the `in-ns` function as the preferred means of getting around in the REPL (and, of course, `ns` is just sugar over it). However, nowhere that I'm aware of on the official docs does it describe the confusing behavior of trying to "switch into" another namespace at runtime, without first having done a `(binding [*ns* *ns*] ...)` block. ([I myself added some comments on the ClojureDocs page, as it had the least friction involved.](https://clojuredocs.org/clojure.core/in-ns)) Strictly speaking, though, someone with some more time should be able to work this explanation into the existing page.

Can we please add either a footnote/warning or a clarification that `in-ns` isn't free and that at runtime a call to `binding` may be required? I ended up being forced to read the source code for the `in-ns` function, `clojure.lang.Var`, `clojure.main`, and `clojure.lang.Compiler` to convince myself of the behavior, when a three line admonition on the official docs should/would have sufficed.

**Comment by puredanger** [comment]
I don't think that binding thing is a good or helpful thing to recommend. `*ns*` is getting modified when you use `in-ns`:

```user=> (in-ns 'foo)
#object[clojure.lang.Namespace 0x10099d2 "foo"]
foo=> clojure.core/*ns*
#object[clojure.lang.Namespace 0x10099d2 "foo"]```

The thing that is most confusing is that `in-ns` does not `(refer-clojure)` (hence the need to refer to `clojure.core/*ns*`, not just `*ns*`).

That said, I think adding some info about this on the namespaces page or elsewhere would be very helpful (a REPL guide is proposed in #218 - that would be another good place).

**Comment by vvvvalvalval** [comment]
Maybe the ['Navigating Namespaces' chapter](https://clojure.org/guides/repl/navigating_namespaces) in the REPL guides now solves this issue? It does not mention the binding-`*ns*` technique (I agree with @puredanger, I would not recommend it) but it does draw distinctions between `ns` and `in-ns`.

**Comment by Artiavis** [comment]
My main issue is that the space I was working in was too low level to really benefit from the intentionally high level allusions you’re referencing about how there may exist subtle differences between those two functions. Of course there’s subtle differences; but the crucial nugget was that all command-line Clojure scaffolds should ensure `*ns*` is properly initialized (if not launching via lein or clojure.main). Perhaps the official docs aren’t the right place to store this knowledge, but I would have appreciated the tip existing somewhere. Maybe not the official docs, but somewhere.

**Comment by puredanger** [comment]
I think the repl guide does now cover the general ns/in-ns stuff that should be mentioned. I think the issue around some initialization paths not initializing `*ns*` are better handled through the ticket in CLJ currently, which should really resolve whether this difference should actually exist (I'd say not). As I'm not sure that there is anything else meaningful to do on this right now, I'm going to close it.
