### ISSUE TITLE
Spec guide: `ranged-rand` function "integer overflow" issue

### ISSUE THREAD

**Issue by jumarko** [clojure/clojure-site#210]
[The implementation of `ranged-rand` function from spec guide](https://github.com/clojure/clojure-site/blob/master/content/guides/spec.adoc#specing-functions) suffers from "integer overflow" problem:
```
(defn ranged-rand
  "Returns random int in range start <= rand < end"
  [start end]
  (+ start (long (rand (- end start)))))
```

Trying to invoke it with following args:
```
(ranged-rand -3800760469044029490 5422611567810746318)
```
cause "integer overflow":
```
ArithmeticException integer overflow  clojure.lang.Numbers.throwIntOverflow (Numbers.java:1521)
```

One possible solution is to use arbitrary precision arithmetic and postpone coercion to long to the very end:
```
(defn ranged-rand
  "Returns a random int such that start <= rand < end."
  [start end]
  (long (+ start
           (bigint (rand (-' end start))))))
```

This problem is usually not revealed when using default num-tests = 1000 for `stest/check`.
However, it manifests almost always when increasing number of tests to 10,000:
```
(stest/check `ranged-rand {::stc/opts {:num-tests 10000}})
;;=> 
({:spec
  #object[clojure.spec.alpha$fspec_impl$reify__1215 0x5b3590a2 "clojure.spec.alpha$fspec_impl$reify__1215@5b3590a2"],
  :clojure.spec.test.check/ret {:result #error {
 :cause "integer overflow"
 :via
 [{:type java.lang.ArithmeticException
   :message "integer overflow"
   :at [clojure.lang.Numbers throwIntOverflow "Numbers.java" 1521]}]
...
```

**Comment by puredanger** [comment]
I am aware of this issue but decided originally that it was worth ignoring for the sake of the example. I will add a note though.

**Comment by sogaiu** [comment]
FWIW, the overflow happens here often enough with the defaults (i.e. for (stest/check `ranged-rand)).

Clojure 1.9.0 on Manjaro Linux.
