### ISSUE TITLE
REPL guide

### ISSUE THREAD

**Issue by raymcdermott** [clojure/clojure-site#218]
There is no simple guide to using a Clojure REPL

[ The only relevant result from searching the site is https://clojure.org/about/dynamic but this not a guide per se ]

I propose this content:

## Choosing a REPL
  - intro to what a REPL experience can provide
  - link to a table of REPLs and their features - that can maintained as the eco-system evolves

## Working with a REPL
  - simple form editing (up / down, left right)
  - paredit / parinfer
  - previous / next forms
  - various affordances / preference settings

## REPL gotchas
  - why does a REPL need to be reloaded?
  - what mitigations exist?

I am happy to push an initial skeleton to get the ball rolling.

**Comment by ivanpierre** [comment]
You've got Arne's "The Ultimate Guide To Clojure REPLs":
https://lambdaisland.com/guides/clojure-repls

**Comment by puredanger** [comment]
FYI, please do not use any material from other sites without permission!

**Comment by jwhitlark** [comment]
https://github.com/bhauman/rebel-readline Is something new that would be worth keeping an eye on.

**Comment by puredanger** [comment]
REPL guide was added last week
