### ISSUE TITLE
Thread macros guide

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-site#22]
Would be nice to have an overview and examples of all the threading macros

**Comment by pesterhazy** [comment]
I've started work [here](https://github.com/pesterhazy/clojure-site/blob/threading-macros/content/reference/threading_macros.adoc). Will flesh out the stub in the next days, unless this is going in the wrong direction, in which case please advise.

**Comment by puredanger** [comment]
ping?

**Comment by pesterhazy** [comment]
PR here: https://github.com/clojure/clojure-site/pull/28

**Comment by puredanger** [comment]
PR #28 was merged
