### ISSUE TITLE
link 404

### ISSUE THREAD

**Issue by paomian** [clojure/clojure-site#227]
https://repo1.maven.org/maven2/org/clojure/clojure/1.9.0-RC2/clojure-1.9.0-RC2.zip 

in [this page](https://clojure.org/community/downloads)

![image](https://user-images.githubusercontent.com/2999156/33369447-990346ac-d52f-11e7-85b0-b74a80c2e9e5.png)

**Comment by puredanger** [comment]
As of 1.9.0-RC2 we've stopped publishing a zip file for the release. Link has been updated to point to the repo directory instead.
