### ISSUE TITLE
contributor agreement

### ISSUE THREAD

**Issue by ocyzl** [clojure/clojure-site#228]
Hmm, do I need to sign the contributor agreement before I can tell you about a typo in the contributor agreement?  Maybe I should wait until it's fixed before signing it.

Anyway, the first option in section 7 is missing a word near the end: it should say "with respect to my contributions", not "with respect my contributions".

**Comment by puredanger** [comment]
You can file issues without signing a contributor agreement. We just need a CA if you are submitting a pull request or a patch.

**Comment by puredanger** [comment]
Regarding the CA, it is a difficult process to update the CA document (there is no “editing” - this would entail creating a whole new doc, which requires a new url, and updating a lot of back-end stuff). So, just not worth it for a typo. Thanks for letting us know though - if there is cause to change it in the future that will be a good time to fix it.
