### ISSUE TITLE
Page for training resources

### ISSUE THREAD

**Issue by timothypratley** [clojure/clojure-site#246]
Clojure is now a desirable buzzword (as well as being jolly useful!)
Enterprise companies are interest in adding Clojure capabilities to their teams, but finding a pre-packaged, structured Clojure training option to purchase is challenging.
This page attempts to make this service easier for companies to locate and purchase Clojure Training.

**Comment by timothypratley** [comment]
https://github.com/clojure/clojure-site/pull/247

**Comment by puredanger** [comment]
Merged last week
