### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by mfikes** [clojure/clojure-site#254]
If you click on the magnifying glass search icon in the upper right and search for, say "type hint" no results are returned.

The only way I've found to search is to use an incorrect url, like https://clojure.org/foo and then use the resulting Google search box.

**Comment by puredanger** [comment]
Yeah, Google shut down the search product we we’re using. I haven’t had time to implement an alternate yet.

**Comment by rauhs** [comment]
Suggestion: Sign up for algolia doc search:

https://community.algolia.com/docsearch/

The actual integration work (JS) could be done by the community.

**Comment by puredanger** [comment]
I’ve heard the suggestion for Algolia. There are other options and support factors around how we deploy this stuff that cross Clojure, ClojureScript, and Datomic sites.

**Comment by puredanger** [comment]
Working again
