### ISSUE TITLE
The tagline is a bit long and somewhat meaningless

### ISSUE THREAD

**Issue by slipset** [clojure/clojure-site#258]
> Clojure is a robust, practical, and fast programming language with a set of useful features that  together form a simple, coherent, and powerful tool.

A useful way to determine if a statement has meaning is to negate it. By doing this, "a set of useful features" becomes meaningless, as most languages, apart from perhaps Brainf!ck are made up of useful features. It is also very common for programming languages to consider themselves robust and practical.

Not all languages are "A fast, functional Lisp running on the JVM"

**Comment by puredanger** [comment]
Rich wrote it, so I'm not going to change it. Generally I find "Lisp" conjures many things, not all of which are correct. And it also runs on the CLR and JS, so I don't think the suggested alternative is better.
