### ISSUE TITLE
Doc ::keys destructuring

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-site#265]
Not currently mentioned in https://clojure.org/reference/special_forms#_map_binding_destructuring or https://clojure.org/guides/destructuring

**Comment by alex-dixon** [comment]
@puredanger Wiling to help if you'd like to see more than what was added in #266

**Comment by puredanger** [comment]
How is that different than what you added in prior?

**Comment by alex-dixon** [comment]
The above shows the destructuring syntax for namespaced keywords with more than two segments. In the last PR we showed destructuring a minimally namespaced keyword eg {:user/keys [name]} {:user/name “Jim”}.

**Comment by puredanger** [comment]
That doesn't seem any different to me, so I guess I'd say I don't think that's worth doing.
