### ISSUE TITLE
Link to clojure style guide

### ISSUE THREAD

**Issue by not-much-io** [clojure/clojure-site#27]
Link: https://github.com/bbatsov/clojure-style-guide 

I personally felt relieved when I found out it existed - I could check my code against the guide and learn from that - "minor" things (vs. functionality), but might help gain confidence nonetheless for beginners.

**Comment by puredanger** [comment]
Somehow I missed this issue when it was logged, but just added. I suspect these resource links will still move around more, but that seems like the best place for it at the moment.
