### ISSUE TITLE
Add `##` syntax to doc page for Clojure reader, and guide to Clojure characters

### ISSUE THREAD

**Issue by jafingerhut** [clojure/clojure-site#281]
The only symbols supported now are `##Inf` `##-Inf` and `##Nan`.  It seems worth listing all of them in the docs.

Reader docs: https://clojure.org/reference/reader
Guide page to add this to: https://clojure.org/guides/weird_characters

I can try drafting something if this is of interest.

**Comment by puredanger** [comment]
Yep, please do - if you need a name these are "symbolic values" - probably a mention about them in the changelog too.

**Comment by jafingerhut** [comment]
Fixed with this commit: https://github.com/clojure/clojure-site/commit/f2eb0e3ae83fbf3ff6222d30a3062d7fd017992c
