### ISSUE TITLE
Responsive Layout: Hide navigation at a wider breakpoint

### ISSUE THREAD

**Issue by focusaurus** [clojure/clojure-site#299]
(Note I read in the contributing guide that style is being worked on, so hopefully this issue can be addressed in the next design iteration. No PR, just an issue and some screenshots).

As your window gets narrower, the space available for the main text and code snippets starts to get crowded out by the left and right navigation, resulting in horizontal scrolling in the code snippets, which makes things really hard to read. This issue is to suggest making the breakpoint where the navigation gets removed much larger, basically as soon as a code snippet would start to horizontally scroll, we should hide the left/right navigation sidebars. Here's some annotated screenshots illustrating the problem:

Over ~1200 all's great.

![clojure-guide-1a](https://user-images.githubusercontent.com/482377/45846614-87ff7a80-bce5-11e8-985c-217e7853e1bf.png)

Around 1150 we're already scrolling in code snippets. I'd suggest hiding the navigation around this size.

![clojure-guide-2a](https://user-images.githubusercontent.com/482377/45846645-9b124a80-bce5-11e8-9898-fed4abd7bbfe.png)
 

Around 750 the content comically squished.

![clojure-guide-3a](https://user-images.githubusercontent.com/482377/45846666-a9f8fd00-bce5-11e8-84d9-43c93eb0c7f5.png)

Then a bit smaller we hide the nav and the content is readable again nicely.

![clojure-guide-4a](https://user-images.githubusercontent.com/482377/45846687-b7ae8280-bce5-11e8-95f7-0ba5270e0853.png)

**Comment by AntoineLefevre** [comment]
In order to contribute to the project and solve this issue, I found a solution by modifying 2 files ( webflow.css & clojureorg.webflow.css ). Since it's not possible to push these files on the repo, I put them at your disposal here. 

Hope it will help !

[css.tar.gz](https://github.com/clojure/clojure-site/files/3908850/css.tar.gz)

**Comment by puredanger** [comment]
Thanks @AntoineLefevre, applied!
