### ISSUE TITLE
Convert contributors list into data

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-site#3]
The current contributor list is maintained manually in [text](https://github.com/clojure/clojure-site/blob/master/content/community/contributing.adoc). As the first step towards automating the contributor list, I need to convert that text list into data (in particular an external csv file with fields for name and github id).

Asciidoc supports inclusion of [tables built from an external csv data file](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#tables).

**Comment by htmfilho** [comment]
I think the section "contributor list" doesn't exist yet in that [page](https://github.com/clojure/clojure-site/blob/master/content/community/contributing_site.adoc). Where exactly would it fit?

**Comment by puredanger** [comment]
Sorry if I was unclear - I mean the list of people who have signed the CA which is already on that page. I would like to actually move that to a new page at /content/community/contributors.adoc and reference it from the contributing page.

**Comment by htmfilho** [comment]
Ah.... I think you mean https://github.com/clojure/clojure-site/blob/master/content/community/contributing.adoc instead of https://github.com/clojure/clojure-site/blob/master/content/community/contributing_site.adoc, right?

**Comment by puredanger** [comment]
Ah, yes! My fault.

**Comment by puredanger** [comment]
Updated issue text to fix it.

**Comment by htmfilho** [comment]
Are you sure you want to separate first name and last name in two different columns?

**Comment by puredanger** [comment]
I was waffling on that (having both facilitates sorting either way). I went back and looked at the CA form and it takes name as a single field, so there is (automated) way to separate these. So, no.

**Comment by htmfilho** [comment]
So, can I put first name and last name in a single column? There are cases like this "**Cognitect, Inc., Justin Gehtland**", which is hard to reason what to do with. Putting in a single column would require no reason at all.

**Comment by puredanger** [comment]
yes, single column

**Comment by puredanger** [comment]
Fixed with pr
