### ISSUE TITLE
atom.io + parinfer

### ISSUE THREAD

**Issue by geraldodev** [clojure/clojure-site#32]
Hi,

A guide for atom.io + parinfer would be awesome.
I've used it to teach some classes where I work.
Unfortunately, I'm not using it daily (I use vim), but I've noticed that It simplifies what scares many newcomers to lisp.
For the repl piece we ended up using the lein repl with require reload.

Regards,

Geraldo

**Comment by puredanger** [comment]
Sure! Plenty of room for guides to tools.

**Comment by puredanger** [comment]
pretty sure this is not needed now

**Comment by iku000888** [comment]
RIP atom editor https://github.blog/2022-06-08-sunsetting-atom/
