### ISSUE TITLE
Document Clojure development and contribution process

### ISSUE THREAD

**Issue by slipset** [clojure/clojure-site#327]
There seems to be quite a bit of noise in the Clojure community stemming from the belief that Clojure is a community effort. 

By adding something along the lines of what @richhickey wrote below on the Contributing page, maybe some of this misunderstanding could be avoided. 

From reddit, https://www.reddit.com/r/Clojure/comments/73yznc/on_whose_authority/

> Clojure was not originally primarily a community effort, and it isn't primarily one now. That has to be ok. The presumption that everything is or ought to be a community endeavor is severely broken. A true community respects the autonomy of its participants, else it degenerates into a cult of need/want.

> Cognitect is a terrific supporter of Clojure, and happens to be where I work, but the ultimate authority and stewardship of Clojure remains with me and I am responsible for the decisions governing it, good or bad.

**Comment by jafingerhut** [comment]
A list of possible pages that could either contain such statements, or at least have a link to where it is made.  This one requires PR to clojure-site repo:

+ https://clojure.org/community/contributing

These are wiki pages that Clojure contributors may edit, but I would prefer that a PR like this one was accepted before adding links to it from these pages:

+ https://dev.clojure.org/display/community/Contributing
+ https://dev.clojure.org/display/community/Contributing+FAQ

**Comment by slipset** [comment]
Also, might help to document the contribution process. 
https://gist.github.com/halgari/c17f378718cbd2fd82324002133ef678#gistcomment-2768972
and 
https://dev.clojure.org/display/community/Developing+Patches

**Comment by puredanger** [comment]
The contribution process is documented in the links Andy posted. There is another existing issue (#163) to move that stuff into the main site but I would like to do that work as it needs some update and modification. Ideally I would like to move everything from that contribution area over and kill off that confluence space.

**Comment by bbatsov** [comment]
@puredanger I think that's a wonderful idea! We certainly would benefit from a consolidated resource on contributing. 

On a more general note - I think that nothing really important should be on the wiki, as I doubt people refer to it as often as they do to the official web site. I guess we can identify the critical articles there, update and migrate them.

**Comment by puredanger** [comment]
I am in the process of doing just that.

**Comment by bbatsov** [comment]
Fantastic!

**Comment by puredanger** [comment]
New page for this at https://clojure.org/community/contributing, still needs further input from Rich and Stu so likely not "done" but we'll continue that off ticket. The prior contributing page  was really about the contributor agreements and is now at https://clojure.org/community/contributor_agreement. Additionally, all useful content from the old wiki was moved to the site last week in a variety of places.

**Comment by puredanger** [comment]
I guess I should also add that this is trying to bring things up to "current state" but does not take into account possible changes in process etc - if/when those happen this will be updated.
