### ISSUE TITLE
Redesign companies page

### ISSUE THREAD

**Issue by slipset** [clojure/clojure-site#332]
It would be nice if the links were clickable, or even better, if the url's were hidden and the names were clickable

**Comment by puredanger** [comment]
It used to be this way but people were contacting me to add companies that I suspect were spam. Assessing that was surprisingly hard to assess, so I removed the motivation to do so.

**Comment by aadrian** [comment]
@puredanger maybe a more convinding approach would be to link companies only if they have a page (or anchor) where Clojure really is mentioned, otherwise anybody can pretend that they use it, but there's no proof, so it also looks like spam.

**Comment by danielcompton** [comment]
@puredanger if you set [`rel="nofollow"`](https://support.google.com/webmasters/answer/96569?hl=en) on those links then search engines won't pass any SEO benefits to the linked site. That would remove most of the motivation for getting links added to clojure.org, although you will always get some spammers trying their luck I guess.

**Comment by puredanger** [comment]
I also went down the nofollow route for a while and would love to make that work. Despite spending a bunch of time on it, I am apparently too dumb to make autodoc do that and eventually gave up. If you can tell me how, I'm all for it.

**Comment by puredanger** [comment]
I know it's not obvious, but I have spent a lot of time on this problem. I share your goals. :)

**Comment by bbatsov** [comment]
👍 Sometimes the problems are more complex than they initially seem. Thanks for the info!

**Comment by danielcompton** [comment]
It looks like this is a [new feature](https://github.com/asciidoctor/asciidoctor/issues/2605) in Asciidoc 1.5.7. e.g.:

```
https://www.google.com[Google,opts=nofollow]
```

The Clojure site uses JBake 2.5.0-SNAPSHOT, and is bundled with AsciidoctorJ 1.5.2. JBake 2.6.3 [uses](https://github.com/jbake-org/jbake/blob/v2.6.3/build.gradle) AsciidoctorJ 1.5.7. To get this you'd either need to update JBake or update the AsciidoctorJ JAR. Not sure which is preferable here?

**Comment by puredanger** [comment]
Upgraded to jbake-2.6.3 and reverted to prior companies page design with links, but added nofollow.
