### ISSUE TITLE
Minor edits to equality guide

### ISSUE THREAD

**Issue by jafingerhut** [clojure/clojure-site#334]
Alex, I will assign this issue to myself if Github gives me permission to do so.  I wanted to record in this issue reminders of minor things that could be improved in the equality guide.  I want to wait to actually create a PR until after Clojure 1.10 is released.

+ Re-check the code examples and return values shown with Clojure 1.10 after it is released.  I do not expect any changes in behavior there, but good to double check and update if necessary.  Update the Clojure version number from 1.9.0 to 1.10.0 near the beginning of the guide.

+ In the "Defining equality for your own types" section, there is a reference to ticket DPRIMAP-12 that has been committed and released in the latest data.priority-map library releases.  Update the text so it no longer references that ticket.

+ Update the link to the 'ordered' library in that same section to its new location in the Github clj-commons organization, and check whether the issue mentioned in the guide is already fixed and released.

+ Consider changing a few more occurrences of `NaN` to `##NaN`, or at least add `##NaN` next to mentions of `Float/NaN` and `Double/NaN`.

+ Scan for "see section <foo>" internal cross references, and add links to the ones that do not have them yet.

+ The references to sections near the end of the article about Henry Baker's EGAL paper should make it clearer that those are sections within that paper, not elsewhere in the guide.

+ In the section "Historical notes on hash inconsistency ...", show how many unique hash values are produced by the current clojure.core/hash function, in addition to how poorly .hashCode behaves.

**Comment by puredanger** [comment]
Sounds good. I don't think you need to do the last bullet. Maybe interesting, but not worth doing here.

**Comment by jafingerhut** [comment]
Closing this issue as the relevant PR has been merged.
