### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [clojure/clojure-site#336]
[The website](https://clojure.org/) lacks IPv6 support.  
Since it seems to use CloudFront, fixing this should be as easy as [enabling IPv6 on the CloudFront distribution](https://aws.amazon.com/blogs/aws/ipv6-support-update-cloudfront-waf-and-s3-transfer-acceleration/) and [creating an AAAA ALIAS record pointing to it](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-cloudfront-distribution.html#routing-to-cloudfront-distribution-config).

**Comment by puredanger** [comment]
done
