### ISSUE TITLE
clojure cheatsheet -- link colors make text hard to read (not enough color contrast)

### ISSUE THREAD

**Issue by zck** [clojure/clojure-site#34]
When looking at the [clojure cheatsheet](http://clojure.org/api/cheatsheet), I find the link colors hard to read, because the contrast is too low for me, on my monitor.

Doing some element inspection in my browser, the link color is defined as `#4C82DF` on a background of `rgba(235, 241, 245, 0.66)`, which converts to `#EBF1F5`. If you throw those values into a [color contrast checker](http://webaim.org/resources/contrastchecker/), it says that it isn't enough contrast for the W3C's [Accessibility Guidelines](https://www.w3.org/TR/WCAG20/).

I think something like `#304890` is much easier to read, while still being a somewhat similar blue. It also passes the W3C guidelines, even the AAA ones.

**Comment by puredanger** [comment]
The cheatsheet is pulled from @jafingerhut 's repo https://github.com/jafingerhut/clojure-cheatsheets so that may be the better place to fix this - maybe file an issue there?

**Comment by puredanger** [comment]
Actually now that I say that, it could actually be a result of css settings here. Anyways, I will take a longer look at it later.

**Comment by zck** [comment]
Thanks for responding! The css settings both come from http://clojure.org/css/clojureorg.webflow.css .

The link color comes from the following rule, starting on line 67:

    a {
      color: #4c82df;
    }

The background color comes from the following rule, starting on line 159:

    *:not(pre) > code {
      display: inline;
      padding-right: 6px;
      padding-left: 5px;
      border-radius: 3px;
      background-color: rgba(235, 241, 245, 0.66);
      font-family: 'Source Code Pro', sans-serif;
      font-size: 16px;
      font-weight: 400;
    }

**Comment by puredanger** [comment]
I made some tweaks to these to darken the link text and modify the background colors for code areas, both pre and non-pre. Same changes on clojurescript.org. I think that helped a lot and this aspect should pass the W3C accessibility guidelines.
