### ISSUE TITLE
Clarify/describe philosophy of Contrib libraries

### ISSUE THREAD

**Issue by seancorfield** [clojure/clojure-site#348]
At this point, some Contrib libraries are core to Clojure itself (spec, tools.deps, clj/brew), some are just continuations of what used to be in "Monolithic Contrib". Some are well-maintained, some do not have an active maintainer at the moment. `tools.nrepl` has forked out of Contrib (and it's not entirely clear what should happen with the version that is still in Contrib). I'm currently designing "next.jdbc" as the next generation of what `java.jdbc` currently is (one of the ones that continued from "Monolithic Contrib") and I haven't decided yet whether to add this to `java.jdbc` within Contrib or create it as a general community library.

When the status of Contrib has been raised in the past, the clear message from the core team is that "Contrib is not a 'Clojure Standard Library'" but, given the development process (CLA, JIRA, patches), Contrib is not a "typical" community project.

Some Contrib libraries are very widely used, others are niche. Some offer functionality that is better-served by a popular community library (`data.json` vs Cheshire comes to mind).

Now that Clojure/core is splitting out features into Contrib -- and those features need to be tightly controlled by the core team -- Contrib seems to be even more of a mixed bag of philosophies.

It would be very helpful -- for Contrib maintainers, and for the broader community -- if there was a clear statement of what it means for a library to be part of the `clojure` organization, part of Contrib. Perhaps even a re-evaluation of whether some of those projects should even be under that core organization at this point?

**Comment by puredanger** [comment]
I've added a new page https://clojure.org/community/contrib_libs and reworked some parts of https://clojure.org/api/api and https://clojure.org/community/libraries. The new page outlines what contrib is (a collection of libs that share a development model) and tries to clarify some of the history.

I think generally too much is made of contrib. It's just a collection of libs with a shared dev model. That's no different than clj-commons or ClojureWerkz. They all have different approaches but each has its own view of how to setup and manage projects.

There is no need to kill, archive, or "release" libs. They've been contributed, their artifacts exist. If someone is well served by the existing release, they should use it. Contrib READMEs should clearly state their status (I'm sure improvements could be made). Users should evaluate the status of each lib and whether it's a good fit for their use, exactly as they would evaluate any other open source. If the current owner has stopped working on it, we're always happy to have someone take it over.

There is no "goal" for contrib beyond providing infrastructure for lib dev. It's just a bunch of libs with a shared dev model.

I'm going to close this ticket now as I think I've achieved the intent. If there are small things in the delta to fix, feel free to comment here though and I'll update. If there are big things, you can file a new issue.

**Comment by seancorfield** [comment]
"Builds - Maven with deployment to Maven Central under the groupId `clojure.org`" -> "... `org.clojure`

I think  that new page accurately describes the current state of the Contrib Libraries. I still think we need discussions around the state/future of individual Contrib Libraries, however. I'd _hoped_ this issue would be a starting point for that discussion :(

**Comment by seancorfield** [comment]
I will add that the new page does, at least, delineate between Contrib Libraries, Core Libraries, and Infrastructure/Not-a-Library within the `clojure` organization so that is definitely "progress" so, thank you for that!

**Comment by seancorfield** [comment]
Stuart's blog post (from 2012) links to https://dev.clojure.org/display/community/Contrib+1.0.0+Releases -- is this still considered valid guidance? I've had mixed responses when I've raised this issue (several times over the last few years).

**Comment by puredanger** [comment]
What’s the question to answer on individual libs? Pretty much every lib is it’s own case, hard to talk generically.

Re contrib 1.0.0, no I don’t think it’s valid anymore. I trust a lib owner to make that decision.

**Comment by seancorfield** [comment]
Re: 1.0.0, I added a clarifying note on that wiki page (pointing back to this issue).

> What’s the question to answer on individual libs? Pretty much every lib is it’s own case, hard to talk generically.

Well, I guess that answers that too then (but not in the way I had hoped).

**Comment by puredanger** [comment]
Turned that list into a table with owners and status.

**Comment by seancorfield** [comment]
Perfect! Thank you, @puredanger -- that's a wonderful clarification of the status of Contrib Libraries!

**Comment by bbatsov** [comment]
Great job with the updated documentation! I think that’s exactly what was needed - now we just have to promote the page a bit when questions about contrib arise. 

One small thing that I think is missing is the “Why?” Of all of this - e.g. why would someone decide to develop a library under contrib. It’d be nice if this was covered somewhere, as it’s certainly puzzling for me.

> There is no need to kill, archive, or "release" libs. They've been contributed, their artifacts exist. If someone is well served by the existing release, they should use it. Contrib READMEs should clearly state their status (I'm sure improvements could be made). Users should evaluate the status of each lib and whether it's a good fit for their use, exactly as they would evaluate any other open source. If the current owner has stopped working on it, we're always happy to have someone take it over.

Fair enough. I think there’s nothing wrong with archiving dead projects, as that sends a very clear message about their status and doesn’t affect the existing artifacts at all. Of course, better READMES go a long way as well. As for killing/releasing stuff - I was mostly referring to the unclear negative impact for the existing projects, that the current arrangement might be having. You made a comparison with clj-commons, but they are not really imposing any restrictions in terms of contributions and infrastructure. One the other hand - Clojure Contrib has historically been criticized mostly in this regard. That’s why I brought up the topic of the rationale for all of this - doing something just for the sake of doing it always struck me as weird. 

Of course, there’s no way to prove the current arrangement is really harmful, so I’ll leave it at that.  Once again - thanks for the great update! Things are now much better than they were and I guess that’s the most important thing at the end of the day.

**Comment by seancorfield** [comment]
My feeling is, at this point, I would expect it to be very unlikely for anyone outside Clojure/core to create a new Contrib library. And I think that's just fine.

Contrib defnitely makes sense for "Clojure Core Libraries", and as a place for existing Contrib libraries to continue being maintained, if the maintainers so desire, but I think it has served the purpose(s) it was originally conceived for at this point.

The new pages cover this history pretty well, I think, and if anyone has a burning desire to create a new library in Contrib -- perhaps because they hold hopes it might be incorporated into Clojure or its Core libraries -- then that's a decision they can make, based on all the information (now) available.

Contrib library maintainers can individually make the decision on whether to continue maintaining a library in Contrib or fork it out of Contrib (as `clojure.tools.nrepl` did) and it's pretty clear what they're giving up: the group ID and the Jenkins/Maven test and deployment pipeline -- and the visibility/governance of the `clojure` organization. They can pick a new group ID, set up Travis/CircleCI, and deploy to Clojars instead -- and make their project visible however they want (and govern it however they want).

**Comment by stuarthalloway** [comment]
The top 5 reasons to create a contrib are:

* common CA
* common CA
* common CA
* common CA
* common CA
