### ISSUE TITLE
Clarify behaviour of `binding`

### ISSUE THREAD

**Issue by mdiin** [clojure/clojure-site#352]
I think many people are unaware of the existence of binding conveyance, and get thrown off by the following comment in the [reference](https://clojure.org/reference/vars):

> Bindings created with binding cannot be seen by any other thread.

A note on binding conveyance here would make a lot of sense.

**Comment by puredanger** [comment]
Updated in f906fe790ce88d2e7da3240e8c6763ee8bed9434
