### ISSUE TITLE
clojure.main instructions don't work anymore

### ISSUE THREAD

**Issue by alandipert** [clojure/clojure-site#361]
I downloaded `clojure-1.10.0.jar` recently and ran `java -jar clojure-1.10.0.jar clojure.main` expecting a REPL, but instead I got an exception with this cause: `java.io.FileNotFoundException: Could not locate clojure/spec/alpha__init.class, clojure/spec/alpha.clj or clojure/spec/alpha.cljc on classpath.`

My understanding of the cause of the exception is that recent versions of Clojure require spec to also be on the classpath.

The instructions on the [The REPL and main entry points](https://clojure.org/reference/repl_and_main) still document `java -jar clojure.jar` which no longer works.

**Comment by puredanger** [comment]
Doh! Thanks. The docs were updated in a couple places (clojure README, getting started page, etc) but missed that one. Will fix.

**Comment by puredanger** [comment]
Updated
