### ISSUE TITLE
Clojure contributor agreement rendering issues

### ISSUE THREAD

**Issue by jrasanen** [clojure/clojure-site#369]
Hi,

the agreement seems to have rendering issues, can anyone else replicate this behaviour or maybe it is a temporary issue with Adobe?

I am able to see the input field labels by making the text-input element active, but can't read the agreement's text content.

I can replicate this using my phone and workstation. (Firefox and Safari)

Screen captures attached below,

<img width="1072" alt="screenshot 2019-03-07 at 7 11 13" src="https://user-images.githubusercontent.com/13303/53934086-f5dc0a80-40a9-11e9-85b3-f38397190318.png">

![img_0408](https://user-images.githubusercontent.com/13303/53934099-07251700-40aa-11e9-8d24-d403db41b52a.PNG)

<img width="597" alt="screenshot 2019-03-07 at 7 26 40" src="https://user-images.githubusercontent.com/13303/53934186-6aaf4480-40aa-11e9-9811-827a5038a691.png">

**Comment by puredanger** [comment]
It's a CORS error with Adobe Echosign. We are aware of it and have been trying to get it fixed but it's not really something we can fix ourselves.
