### ISSUE TITLE
Missing documentation on function body structure

### ISSUE THREAD

**Issue by aaronang** [clojure/clojure-site#379]
Hi 👋

I was reading the ["Learn Clojure - Functions"](https://clojure.org/guides/learn/functions) guide and got stuck at the `triplicate` question. For some reason, I assumed that the body of the function definition could only be a single expression instead of multiple. I think it isn't clearly mentioned that the function body could consist of multiple expressions. Did I miss it? If not, I am willing to improve the documentation or we could make this a "beginner friendly" issue 😄

**Comment by puredanger** [comment]
Isn't this covered in https://clojure.org/guides/learn/functions#_multi_arity_functions ?

**Comment by puredanger** [comment]
Or are you talking about the body of a function being multiple expressions? If so, happy to get a PR that clarifies that, probably at the very top of that page in the first section.

**Comment by aaronang** [comment]
@puredanger Correct, I was talking about the function body being able to consist of multiple expressions. It is actually mentioned here:

> Each arity is a list `([args*] body*)`. One arity can invoke another.

But it is kind of hidden in my opinion.
