### ISSUE TITLE
Confusing sentence on frontpage

### ISSUE THREAD

**Issue by brian-dawn** [clojure/clojure-site#38]
Tried to find the index.adoc page so I could make the change myself but that doesn't appear to be here.

The error from `http://clojure.org/index`:

```
Additionally, Clojure’s maps, sets, and vectors are as first class in Clojure 
are lists are in Lisp.
```

Should be

```
Additionally, Clojure’s maps, sets, and vectors are as first class in Clojure 
as lists are in Lisp.
```

**Comment by puredanger** [comment]
The home page content is the only page built as part of the theme itself, so is not in the repo. Fixed for next deploy.
