### ISSUE TITLE
Add RSS or Atom feed for the News section

### ISSUE THREAD

**Issue by alexott** [clojure/clojure-site#39]
It would be nice to add feed for this section, so the news could be propagated to Planet Clojure.

**Comment by puredanger** [comment]
I should be able to generate this from a template, will look into it.

**Comment by puredanger** [comment]
http://clojure.org/feed.xml now exists - how does that look @alexott ?

**Comment by arrdem** [comment]
:+1:

**Comment by puredanger** [comment]
Well, closing for now, let me know if something looks awry!

**Comment by alexott** [comment]
Thank you! Will add it today evening...
