### ISSUE TITLE
jbake instructions need updating?

### ISSUE THREAD

**Issue by jafingerhut** [clojure/clojure-site#396]
I can propose a PR for this if you also have this issue, but wondered if I have set up things wrongly somehow.

When I follow the instructions in the file README.adoc to install jbake-2.6.3, when I try running the command `jbake` with no command line options as recommended there, I get a "Usage" message and no document processing occurs.

I have found that running with the command line: `jbake . output` pretty much works, with the caveat that it create a directory with a space at the beginning of the name, i.e. ` output` instead of `output`.  Is this also the command you use?

**Comment by puredanger** [comment]
Updated, just needs to be `jbake -b`.
