### ISSUE TITLE
Answers of "Test your knowledge" sections

### ISSUE THREAD

**Issue by RodrigoCSoares** [clojure/clojure-site#407]
There are great exercises titled "Test your knowledge" at the "Learn Clojure" guide. However, there is no answer provided to those exercises so it can be frustrating for the learner.

- Link for one of those sections: https://clojure.org/guides/learn/functions#_test_your_knowledge

**Comment by puredanger** [comment]
Thanks, I keep meaning to add those :)

**Comment by puredanger** [comment]
Added. https://clojure.org/guides/learn/answers
