### ISSUE TITLE
Namespace introduction/guide is needed

### ISSUE THREAD

**Issue by seancorfield** [clojure/clojure-site#419]
The only material about namespaces on clojure.org seems to be https://clojure.org/reference/namespaces and https://clojure.org/reference/libs -- neither of which are useful to beginners (who will end up here via searches for `namespace`).

Adding something to the "learn" pages would be a good place to start since that currently just covers expressions entered in the REPL and doesn't talk about source files, and the associated naming conventions and use of namespaces.

And perhaps add a "guide" page about namespaces too?

**Comment by puredanger** [comment]
I've added:

* a page at https://clojure.org/guides/learn/namespaces
* a link from https://clojure.org/reference/namespaces to there

If you search for "clojure namespaces", those are the top two links.

The libs page is a lingering question. This page has useful info and uses "lib" in the sense of a namespace, matching many 1.0-era docstrings, but does not match modern usage of the term "lib" (referring usually to a whole library, not a namespace). I will need Rich's input on that and I'm going to file a more targeted ticket just about this.

**Comment by seancorfield** [comment]
This is great! Thanks, @puredanger !

**Comment by puredanger** [comment]
I actually added it 4 months ago, just forgot to update here. :)

**Comment by seancorfield** [comment]
Haha... well, it's not something I would have found on my own so I can only say that no beginners have asked me about namespaces in the last four months. But I'll keep my eyes open for future conversations and point them at it, now I know it's there.
