### ISSUE TITLE
Should have clojure code on the front page

### ISSUE THREAD

**Issue by ShaneKilkelly** [clojure/clojure-site#43]
Most devs will expect to see some example code when visiting the home-page of a programming language. Currently clojure.org has none.

Examples of language home-pages with tasteful code blocks:

- Ruby (https://www.ruby-lang.org/en/)
- Python (https://www.python.org/)
- Elixir (http://elixir-lang.org/)
- Racket (http://racket-lang.org/)

**Comment by puredanger** [comment]
We have decided not to do that for now.

**Comment by mzavarella30** [comment]
Is there any reason for this? I think having an example of the code on the front page would be very beneficial. One of the purposes of the home page is to catch the eye of a 'new' reader and right now nothing about the site right now is really eye catching. Unless the front page is going to change in a major way, there should be a small bit of code or a couple of code examples on a carousel to draw people in.
