### ISSUE TITLE
The layout seems broken on certain resolutions

### ISSUE THREAD

**Issue by j-cr** [clojure/clojure-site#439]
See the screenshots:

![Screenshot1](https://user-images.githubusercontent.com/41063058/70056355-26cb7a80-15fd-11ea-9281-a8d91aeccaea.png)
![Screenshot2](https://user-images.githubusercontent.com/41063058/70056356-27641100-15fd-11ea-847b-4ddab044420b.png)

**Comment by puredanger** [comment]
Seems to be a result of changes in #299 which I have now rolled back.
