### ISSUE TITLE
unquote explanation missing important information

### ISSUE THREAD

**Issue by sogaiu** [clojure/clojure-site#440]
The current explanation of unquote in the "Reading Clojure Characters" (https://clojure.org/guides/weird_characters#unqote) section is:

> ~ is unquote. That is within a syntax quoted ` form ~ will unquote the associated symbol, i.e. evaluate it in the current context

That seems correct, but there is no mention (there or later in that section) that the unquoting or evaluation could work for things other than symbols.  That seems like a rather important omission.

The unquote section has a reference to the syntax quote section:

> See ` for additional information.

but I don't see the relevant info there either.

Please consider enhancing the unquote section's explanation.

(On a side note, 2 of the 3 references in the unquote section to other docs on macros are helpful for this particular point, so was grateful for those :)  But I wouldn't have known to look if I didn't happen to already be suspecting that the explanation was incomplete.)

**Comment by puredanger** [comment]
Sounds like a good idea

**Comment by sogaiu** [comment]
Thanks!
