### ISSUE TITLE
Testing Guide

### ISSUE THREAD

**Issue by nate** [clojure/clojure-site#444]
It would be nice if there was some mention on the [Deps and CLI](https://clojure.org/reference/deps_and_cli) page, or another page, about how to set up a test runner for clojure projects using the built-in CLI and dependency management. I thought I was missing something but it turns out there's no built-in test runner and noting this might save others time in the future.

Thanks!

**Comment by seancorfield** [comment]
The guide mentions adding a test source directory to the classpath (but gives no indication of how to _run_ those tests): https://clojure.org/guides/deps_and_cli#extra_paths

That would seem to be a good place to at least mention test runners (and perhaps link to https://github.com/clojure/tools.deps.alpha/wiki/Tools#testing ).

If `clojure.test` gets split out as a Contrib library, it will provide an opportunity to greatly expand the documentation around using it, to include an overview of popular runners, and making it easier to folks to learn how to use `clojure.test` effectively.

**Comment by puredanger** [comment]
I added this recently at https://clojure.org/guides/deps_and_cli#test_runner
