### ISSUE TITLE
Wrong `elide-meta` example value suggested

### ISSUE THREAD

**Issue by vemv** [clojure/clojure-site#445]
https://clojure.org/reference/compilation#_compiler_options suggests:

```
-Dclojure.compiler.elide-meta="[:doc :file :line :added]"
```

However the double-quotes seem extra and end up causing an error.

Only the following works in e.g. a Lein project:

```diff
-{:jvm-opts ["-Dclojure.compiler.elide-meta=\"[:doc :file :line :added]\""]}
+{:jvm-opts ["-Dclojure.compiler.elide-meta=[:doc :file :line :added]"]}
```

**Comment by puredanger** [comment]
The example given is a Java command line example. The example you're providing is Leiningen specific, and not everyone uses Leiningen. The system property value needs to include spaces and how that happens will necessarily be dependent on the launcher used.

**Comment by vemv** [comment]
TIL, thanks!

The following also works:

```diff
- java -Dclojure.compiler.elide-meta="[:doc :file :line :added]" ...
+ java "-Dclojure.compiler.elide-meta=[:doc :file :line :added]" ...
```

i.e. CLIs support two syntaxes for passing the same value. The one that https://clojure.org/reference/compilation#_compiler_options suggests might be a bit less portable (CLI -> Lein).

**Comment by puredanger** [comment]
Seems reasonable, updated.
