### ISSUE TITLE
Missing HTTPS on clojure.org links

### ISSUE THREAD

**Issue by jbampton** [clojure/clojure-site#454]
<img width="860" alt="Screen Shot 2020-03-18 at 3 53 45 pm" src="https://user-images.githubusercontent.com/418747/76930013-3c0cb080-6931-11ea-984b-8c2aa2e5f0e9.png">

<img width="893" alt="Screen Shot 2020-03-18 at 3 54 44 pm" src="https://user-images.githubusercontent.com/418747/76930031-44fd8200-6931-11ea-91c3-c37fe9f379d7.png">

**Comment by puredanger** [comment]
Fixed
