### ISSUE TITLE
Add more Clojure Books

### ISSUE THREAD

**Issue by aadrian** [clojure/clojure-site#456]
Hi,

The following books:
 1. https://www.packtpub.com/programming/the-clojure-workshop
 2. https://www.packtpub.com/programming/clojure-polymorphism  (2019 Packt Edition)
 3. https://www.packtpub.com/application-development/microservices-clojure

don't seem to be present on the https://clojure.org/community/books page, even if they are published a while ago.

Thank you.

**Comment by puredanger** [comment]
Added
