### ISSUE TITLE
Is the reader really side-effect free?

### ISSUE THREAD

**Issue by hexagonrecursion** [clojure/clojure-site#460]
I see a contradiction between this
https://github.com/clojure/clojure-site/blame/master/content/reference/lisps.adoc#L20
> * The reader is side-effect free

and this
https://clojure.org/guides/weird_characters#_reader_eval
> user=> (read-string "#=(println :foo)")
:foo
nil

**Comment by puredanger** [comment]
Reader eval is not a public or supported feature of the reader. I've removed it from the weird characters guide.
