### ISSUE TITLE
Keywords are not symbols

### ISSUE THREAD

**Issue by hexagonrecursion** [clojure/clojure-site#461]
https://clojure.org/guides/learn/syntax#_symbols_and_idents
> Symbols that start with a leading colon are called keywords.

This implies that keywords are symbols, but they are not: `(symbol? :foo)` returns false. This is the worst kind of lie - it is almost true: keywords and symbols behave identically in many situations. This can seriously confuse new users.

**Comment by puredanger** [comment]
Fixed, thanks.
