### ISSUE TITLE
Proposal: would you please add one line introduce to each library?

### ISSUE THREAD

**Issue by netroby** [clojure/clojure-site#47]
http://clojure.org/api/api
In this page , we list these libraries:
Clojure Contrib Libraries

algo.generic
algo.graph
algo.monads
core.async
core.cache
core.contracts
core.incubator
core.logic
core.match
core.memoize
core.rrb-vector
core.typed
core.unify
data.avl
data.codec
data.csv
data.finger-tree
data.fressian
data.generators
data.json
data.priority-map
data.xml
data.zip
java.classpath
java.data
java.jdbc
java.jmx
math.combinatorics
math.numeric-tower
test.generative
tools.analyzer
tools.analyzer.js
tools.analyzer.jvm
tools.cli
tools.emitter.jvm
tools.logging
tools.macro
tools.namespace
tools.nrepl
tools.reader
tools.trace

But would you please add one line introduce to each library ? to help new user to easy know what the library does quickly.

**Comment by puredanger** [comment]
Sounds like a good idea

**Comment by puredanger** [comment]
accepted PR
