### ISSUE TITLE
Code block syntax highlighting inconsistent

### ISSUE THREAD

**Issue by Anders-E** [clojure/clojure-site#471]
Code blocks seem to rely on the language auto-detection feature from highlight.js instead of explicitly declaring that they should be highlighted as if they were Clojure code.

This leads to inconsistent and often incorrect syntax highlighting.

## Example

The following example is from https://clojure.org/guides/learn/syntax#_character_types

### What it looks like

![img](https://user-images.githubusercontent.com/11639036/88505941-19725e80-cfd9-11ea-8f5e-186ec27a8a5d.png)

### What it should look like

![img](https://user-images.githubusercontent.com/11639036/88506002-4292ef00-cfd9-11ea-804e-72b48efc19eb.png)

A quick look at the HTML shows that this specific block was auto-detected as Bash:

```html
<code data-lang="clojure" class="hljs bash">
```

**Comment by puredanger** [comment]
Thanks, I might have broken this with a recent change... will take a look.

**Comment by puredanger** [comment]
Actually, has probably always been broken. :)  Fixed thanks to @admiralbumblebee!
