### ISSUE TITLE
include info for calling java methods with varargs on java_interop page

### ISSUE THREAD

**Issue by dpsutton** [clojure/clojure-site#478]
a common question/gotcha is understanding how to call java methods which have varargs in their signature. A recent example came up with calling a method `Page<Project> list(ProjectListOption... options)`. The person was following example code from the readme which omitted any args: `Iterator<Project> projectIterator = resourceManager.list().iterateAll();` and then was confused why just calling `(.list resource-manager)` was throwing an error.

This seems to come up relatively often and I believe merits a mention in this guide. Thanks

**Comment by dpsutton** [comment]
slack user `kenny` helpfully pointed out that a section like this exists in the faq under java and interop. I believe this information just needs to be referenced or copied into the java reference.

**Comment by puredanger** [comment]
Added section to java interop and linked to faq
