### ISSUE TITLE
Using local libraries needs a beginner friendly example.

### ISSUE THREAD

**Issue by bigos** [clojure/clojure-site#479]
https://www.clojure.org/guides/deps_and_cli#_using_local_libraries
In the link above you have this code example:

> Modify hello-world/deps.edn to use a local coordinate that refers to the root directory of the time-lib library (make sure to update the path for your machine):
> 
> ```
> {:deps
>  {time-lib/time-lib {:local/root "/path/to/time-lib"}}}
> ```
> 
> 

This makes no sense to a beginner and need s an example. 

What is the path supposed to be? Is it an absolute path?  Am I supposed to add the file name? 

At this point a beginner possibly did not see `:local/root` and googling for it does not lead to anything that would make sense.

Could you give a better example?

Which one is correct? Did I miss some other possibilities?

- {:local/root "/home/ahmed/dev/Clojure/hello/time-lib/hello.clj"}
- {:local/root "/hello/time-lib/hello.clj"}
- {:local/root "home/ahmed/dev/Clojure/hello/time-lib/hello.clj"}
- {:local/root "hello/time-lib/hello.clj"}
- {:local/root "/home/ahmed/dev/Clojure/hello/time-lib"}
- {:local/root "/hello/time-lib/"}
- {:local/root "home/ahmed/dev/Clojure/hello/time-lib/"}
- {:local/root "hello/time-lib/"}

**Comment by bigos** [comment]
It turns out that this works:

```
{:deps
 {time-lib/time-lib {:local/root "time-lib"}}}
```

I also have tried longer path that works:
```
{:deps
 {time-lib/time-lib {:local/root "/tmp/Experiments/hello/time-lib"}}}

```
Which works because I put my clojure experiment in the temp folder when I tried to redo everything from scratch.

Does this mean that `:local/root` is the path of the parent deps.edn file pointing to folder of  the child deps.edn file?

### Additional Confusion

When I got stuck with the path I did not notice my file structure was wrong.

The file `hello_time.clj` was supposed to be in `time-lib/src` not `time-lib`.

I think I would have found it quicker if the path was more specific.

**Comment by puredanger** [comment]
Updated to use relative path
