### ISSUE TITLE
Description of evaluation appears slightly off

### ISSUE THREAD

**Issue by sogaiu** [clojure/clojure-site#485]
Recently I was helped by the description of evaluation that I found at: https://clojure.org/reference/evaluation in trying to understand what happens in code such as:
```
$ clj
Clojure 1.10.1
user=> ((symbol "+") 1 8)
8
```
The description on that page was valuable in improving my mental model of evaluation.  Thank you.

However, I became confused trying to reconcile what happens for the following code:
```
$ clj
Clojure 1.10.1
user=> (1 (spit "hello" "/tmp/hi.txt"))
Execution error (ClassCastException) at user/eval1 (REPL:1).
java.lang.Long cannot be cast to clojure.lang.IFn
user=> (.exists (java.io.File. "/tmp/hi.txt"))
false
```
and a reading of the following paragraph at the aformentioned page:

> If the operator is not a special form or macro, the call is considered a function call. Both the operator and the operands (if any) are evaluated, from left to right. The result of the evaluation of the operator is then cast to IFn (the interface representing Clojure functions), and invoke() is called on it, passing the evaluated arguments. 

I think a fair interpretation of the paragraph is that the evaluation of the operator and operands occur before the operator is cast to IFn.  But I think that interpretation is a bit off -- if it were correct, I think in the example above, a file should have existed by the end, but AFAICT, it does not.  

IIUC the casting of the operator is attempted after the operator evaluation, but only if this succeeds is operand evaluation tried.

My guess is that the following bit of code is a portion of what the text description corresponds to: https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Compiler.java#L3700-L3703

(Thanks to John Hume's [The Life of a Clojure Expression](https://www.duelinmarkers.com/2016/01/24/the-life-of-a-clojure-expression.html) for hints)

Please consider modifying the text description.

Some candidate concrete suggestions include:

* Order the description in a way to more closely match what happens.  Specifically, describe the casting as occurring before the operands being evaluated.
* Remove the word "then" from the sentence beginning "The result of the evaluation fo the operator is then cast to IFn"
* Add a link to the relevant source / describe where to look in the source to get a more detailed idea.

In any case, thank you for the existing description of the evaluation.

**Comment by puredanger** [comment]
I removed the word "then" to clarify order - the error here occurs while evaluating the operator.
