### ISSUE TITLE
weird_characters.adoc missing weird characters from the second sample

### ISSUE THREAD

**Issue by 42degrees** [clojure/clojure-site#492]
I was looking at the "weird_characters" page (titled "Reading Clojure Characters") and the second sample is "user=> (get ["a" 13.7 :foo] 1)" but nowhere on that page is any description of the "=>" symbol, one of the hardest to Google because of the greater-than sign.  So, then I went to the "syntax" page and found that, wow that symbol is used all over that page, but isn't defined there either.  Seems like a pretty important symbol to be used so often, you'd think it would get some primary documentation.  

I went through every page in "Guides" and not a one defines this ubiquitous operator.  I searched through the entire "Spec" page and found lots of uses of "=>" but all in comments (and the few that weren't in a comment probably were intended to be but the ';' was missing).  

I still have only guesses as to what it means.

**Comment by sogaiu** [comment]
IIUC, by convention that's used to indicate a prompt -- if you try it out at a Clojure REPL, you'll probably see something like:
```
$ clj
Clojure 1.10.1
user=> =>
Syntax error compiling at (REPL:0:0).
Unable to resolve symbol: => in this context
user=> 
```

Sometimes other things are used in lispy languages.

**Comment by 42degrees** [comment]
> IIUC, by convention that's used to indicate a prompt -- if you try it out at a Clojure REPL, you'll probably see something like:
> 
> ```
> $ clj
> Clojure 1.10.1
> user=> =>
> Syntax error compiling at (REPL:0:0).
> Unable to resolve symbol: => in this context
> user=> 
> ```
> 
> Sometimes other things are used in lispy languages.

Thanks for the information.  That actually had occurred to me, but then it didn't explain examples like these:
user=> (def x "x") ; this is a comment
#'user/x
user=> (def players #{"Alice" "Bob" "Kelly"})
#'user/players
user=> (defn foo [x]
         (case x
           5 "x is 5"
           10 "x is 10"))
#'user/foo

The result of evaluating the line has the part before the => in it, which I took as an indication that it was processed by Clojure.  So, my best guess was that user=> was defining a namespace or something similar.  That's not to mention lots of examples that don't start with "user=>".  

After reading your reply I did find the deps_and_cli page which shows running the CLI, but does not explain what "user=>" actually means.  What's the point of printing out the word "user?"  Are there circumstances when "user" would be some other string?

I would probably have figure that out if and when I figure out how to run it locally.  I was expecting to find a download for a Closure compiler, but I'm guessing now that the only way to run Clojure is as a script.  I'm also confused with the use of CLI (Command Line Interface) and CLJ (Command Line J???).  I'll keep reading through the site...

Thanks again.

**Comment by 42degrees** [comment]
OK, I guess Clojure isn't really ready for prime time on Windows, but I did find an online Clojure site to try some code samples (https://www.tutorialspoint.com/execute_clojure_online.php).  No mention on there of "user" and running the examples above, that had user in the displayed results, does not produce the displayed result (no output is produced by any of those code samples).

**Comment by sogaiu** [comment]
@42degrees If you don't mind using slack, there is a #beginners channel typically with helpful people.

FWIW, that's: https://clojurians.slack.com/
