### ISSUE TITLE
Add book entry for Numerical Linear Algebra for Programmers

### ISSUE THREAD

**Issue by blueberry** [clojure/clojure-site#498]
Book title: Numerical Linear Algebra for Programmers: An Interactive Tutorial with GPU, CUDA, OpenCL, MKL, Java and Clojure
URL: https://aiprobook.com/numerical-linear-algebra-for-programmers/
Publisher: Dragan Rocks
Publishing Date: 2021-01-15 (RC1, updated continuously)

(The code is 100% Clojure, even though it's not been given the spotlight in the title)

**Comment by puredanger** [comment]
added
