### ISSUE TITLE
Link to Clojurians Slack Chat is no longer active

### ISSUE THREAD

**Issue by IRLeif** [clojure/clojure-site#505]
I'm new to Clojure and I would like to join the Clojurians Slack Chat, but the link provided on [this page](https://clojure.org/community/resources) is no longer active.

Visiting the link says:

> "This link is no longer active. To join this workspace, you’ll need to ask the person who originally invited you for a new link."

I don't know whom to contact, so I figured it would be best to create an issue here to get the link fixed.

**Comment by puredanger** [comment]
Hi, that is weird and I am checking with the Clojurians Slack maintainers.

**Comment by seancorfield** [comment]
@IRLeif This link will work for a couple of weeks: 👋  Let’s move this to Slack! We’ve got 20472 folks from the team there already. You can sign up here: https://join.slack.com/t/clojurians/shared_invite/zt-lsr4rn2f-jealnYXLHVZ61V2vdi15QQ

We're working on getting `clojurians.net` updated (which has nothing to do with the team that maintains `clojure.org` so this issue can be closed).

**Comment by puredanger** [comment]
I’m going to close per Sean’s comment, seems like the link is correct but they are working on it

**Comment by IRLeif** [comment]
Perfect, thanks guys!
