### ISSUE TITLE
UUID Tagged Literal Example

### ISSUE THREAD

**Issue by brettrowberry** [clojure/clojure-site#508]
https://github.com/clojure/clojure-site/blob/master/content/reference/reader.adoc mentions Instant and UUID tagged literals. 
There is an example of Instant, `#inst "2014-05-19T19:12:37.925-00:00"`.
Could a UUID example please be added?

**Comment by puredanger** [comment]
There is one right below #inst. ?

**Comment by puredanger** [comment]
closing pending more info as it seems to be there
