### ISSUE TITLE
Please add Clojure eXchange 2016 Event to events page

### ISSUE THREAD

**Issue by chrishowejones** [clojure/clojure-site#51]
Clojure eXchange 2016 

If you're looking for the best place to learn about Clojure, Functional Programming and network with like-minded people, then the Clojure eXchange 2016 is the conference you simply can't miss! Meet with the world's leading experts, learn how to use Clojure in your team and discuss war stories with your peers.

Location: CodeNode, London, UK
Link: https://skillsmatter.com/conferences/7430-clojure-exchange-2016
Dates: 1st-2nd December 2016

**Comment by puredanger** [comment]
added
