### ISSUE TITLE
Please add ClojureBridge London to Clojure.org events page

### ISSUE THREAD

**Issue by chrishowejones** [clojure/clojure-site#52]
ClojureBridge London 2016

We're offing this workshop to help make the Clojure community more accessible to a diverse range of participants. As such, this event is only welcoming participants who identify as female or nonbinary. Males may register as a guest of one of these participants.

This workshop is intended for those with none/some programming experience. 

Link: http://www.clojurebridge.org/events/2016-02-19-london
Location: London, UK
Dates: 19th-20th February 2016

**Comment by puredanger** [comment]
added
