### ISSUE TITLE
Learning Clojure - Functions: missing placeholders, proportional font for code listings

### ISSUE THREAD

**Issue by nmtake** [clojure/clojure-site#520]
Currently, https://clojure.org/guides/learn/functions displays 
as follows (tested with Firefox 87.0/Linux):

----

![20210408_23h01m59s_grim](https://user-images.githubusercontent.com/18096192/114040250-66276c80-98be-11eb-8e6a-5ba2bdcafd07.png)

----

As we can see, the placeholders `___` in Q1 are missing,
text in Q1 is unintentionally italicized,
and the code listing in Q3 is displayed with spaced font.

As per the Asciidoctor references, I think following changes should work:

1. use `'+text+'` (please replace single quotes with backquotes) for [literal monospace text](https://docs.asciidoctor.org/asciidoc/latest/text/monospace/#literal-monospace); the plus marks passthrough given text but escapes HTML special characters. The behavior differs from original Asciidoc - introduced in [Asciidoctor 1.5.0](https://asciidoctor.org/release-notes/asciidoctor-1-5-0/#spotlight-syntax).
2. separate each block with a newline to apply block attributes
(`[source,clojure]` in this case) to the block correctly.

**Comment by puredanger** [comment]
Thanks, fix deploying!
