### ISSUE TITLE
tools.deps.alpha API docs describe the deprecated make-classpath 

### ISSUE THREAD

**Issue by lread** [clojure/clojure-site#521]
I noticed that [make-classpath is now marked as deprecated](https://github.com/clojure/tools.deps.alpha/blob/9bf5778dc26dd5018dbf04fc8e7dbb32ddc4036c/src/main/clojure/clojure/tools/deps/alpha.clj#L611) but [the tools.deps.alpha API docs still refer to it](https://github.com/clojure/tools.deps.alpha/blob/master/API.md).

**Comment by puredanger** [comment]
That API page is really unnecessary at this point, so I've removed it and refreshed the tools.deps api docs.
