### ISSUE TITLE
Add Discljord and/or Clojurians Discord server.

### ISSUE THREAD

**Issue by wildwestrom** [clojure/clojure-site#525]
- [x] Read the guidelines for contributing?
- [x] Signed the Clojure Contributor Agreement.
- [x] Verified the asciidoc markup is correct.

I would love some more face-to-face interaction in the community. 
Streaming my work and doing pair programming is pretty fun.
The larger the server, the more spontaneous opportunities for this kind of interaction.

`clojure-site/content/community/resources.adoc`:
```diff
== Clojure Discussion

  * https://ask.clojure.org[Q&A Forum] (official)
  * https://groups.google.com/group/clojure[Clojure Google Group] (official)
  * http://clojurians.net[Clojurians Slack Chat]
  * https://clojurians.zulipchat.com[Clojurians Zulip Chat]
  * https://clojureverse.org[Clojureverse]
  * https://clojure.org/community/user_groups[Clojure User Groups]
  * http://planet.clojure.in/[Planet Clojure] blog aggregator
  * #clojure IRC channel on https://freenode.net[freenode.net]
+ * https://discord.gg/discljord[Discljord Clojure Discord Server]
+ * https://discord.gg/MsejPv9JNG[Clojurians Discord Server]
```
The Discljord is a more moderated than Clojurians, but Discljord also dedicated to writing bots for Discord in Clojure, where Clojurians is more generally Clojure focused.

**Comment by puredanger** [comment]
One of these discords is linked in that list already (bullet #4) so need to dedupe. 

Also, I need you to sign the contributor's agreement https://clojure.org/dev/contributor_agreement

Thanks!

**Comment by wildwestrom** [comment]
Got it, I updated the snippet.

**Comment by puredanger** [comment]
Oh, sorry, I thought this was a PR for some reason! I can make these mods and you don't need to sign the CA for this.
