### ISSUE TITLE
Typo in "agents.adoc": Use same variable names in doc as in code snippet

### ISSUE THREAD

**Issue by frwdrik** [clojure/clojure-site#539]
In the following documentation, the variable names `m` and `n` seem to denote the opposite thing in the doc and in the code snippet directly below it, in the file `clojure-site/content/reference/agents.adoc` 
"""
This example is an implementation of the send-a-message-around-a-ring test. A chain of n agents is created, then a sequence of m actions are dispatched to the head of the chain and relayed through it.
"""

**Comment by puredanger** [comment]
thanks, fixed!
