### ISSUE TITLE
Error on Clojure eXchange event

### ISSUE THREAD

**Issue by chrishowejones** [clojure/clojure-site#54]
On the http://clojure.org/community/events page the date for Clojure eXchange shows as 2016-12-02 but the first day of the conference is actually 2016-12-01.

**Comment by puredanger** [comment]
that looks like a template bug showing end date rather than start date, will fix

**Comment by chrishowejones** [comment]
Thanks Alex

**Comment by puredanger** [comment]
fixed for next deploy
