### ISSUE TITLE
Incorporate a "try/clojure" REPL

### ISSUE THREAD

**Issue by mtnygard** [clojure/clojure-site#55]
See the home page for Rust: https://www.rust-lang.org/

Try/clojure is a lovely project, but the casual browser of clojure.org won't know how to interpret "TryClojure provides a browser-based Clojure REPL" and may not click through.

To elaborate, if I follow the path "clojure.org" -> "clojure.org/getting_started" as a new user, the term REPL is as yet undefined for me. So I won't know that "a browser-based Clojure REPL" means "play with some Clojure code in your browser."

On the other hand, if there's an edit box with code in it and a "run me" button, then it's pretty clear what I'm looking at.

**Comment by Raynes** [comment]
Author of tryclj here. I just put this on iRC:

>[22:54:44]  <Raynes>	While I appreciate the reference to tryclj.com, I haven't maintained it in literally years and probably won't for at a minimum 3 months. It's old, broken in mysterious ways a lot, and I have generally completely ignored reported issues. It might not be worth being on there unless someone wants to help me out with maintaining and updating it (I can work with you a bit, just busy with other things most of the time, you'd be given admin on the repo) or wait on my completely detached a** to return from the void.
>[22:55:59]  <justin_smith>	Raynes: I think contacting cognitect or the clojure-dev mailing list would get you in touch with the right person
>[22:56:55]  <Raynes>	I'll hit the clojure-dev mailing list methinks, since I'm also asking for help.
>[22:57:29]  <domgetter>	Raynes: Thanks for the awesome website :)
>[22:57:55]  <Raynes>	The one with the ancient Clojure version and half-broken sandbox? You're welcome good sir.
>[22:58:05]  <Raynes>	:p
>[22:58:25]  <Raynes>	Guys I'm so deep in Python I feel like a mouse.

So, that's my story. I don't think tryclj is production enough to be on such a fancy Clojure website, particularly as an an introductory first-glance for more.. professional folks.

I'm going to look for anyone to help me maintain the site as per the above IRC quote, and I will eventually get to it, but for now... Eh. I have grand, beautiful plans with dropping clojail and going JVM-per-session scalability, but it'll take a bit.

**Comment by viebel** [comment]
Maybe the klipse plugin could help?
http://blog.klipse.tech/clojure/2016/06/07/klipse-plugin-tuto.html

**Comment by viebel** [comment]
Here is how the destrucuting guid  would look like (simulated integration of th klipse plugin with userscript): https://www.youtube.com/watch?v=D8DKbUmZrlQ

**Comment by yogthos** [comment]
I definitely think klipse would be the way to go here.

**Comment by leifericf** [comment]
Perhaps https://tryclojure.org could be embedded on the landing page of https://clojure.org?

**Comment by S-reinken** [comment]
I'd like to see what a https://tryclojure.org embed would look like, and I can manually put it in the index.ftl file, but since those templates aren't in source control I'm not sure how to suggest it in a pull request.

**Comment by puredanger** [comment]
At Rich’s guidance, he did not want that on the site, which is why it’s not there now.
