### ISSUE TITLE
Transducers claim cat doesn't take an `rf`

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojure/clojure-site#559]
But it does!

> In some cases, like cat, the core function is a transducer function and does not take an rf.

```
Clojure 1.10.3
user=> (source cat)
(defn cat
  "A transducer which concatenates the contents of each input, which must be a
  collection, into the reduction."
  {:added "1.7"}
  [rf]
  (let [rrf (preserving-reduced rf)]  
    (fn
      ([] (rf))
      ([result] (rf result))
      ([result input]
         (reduce rrf result input)))))
nil
```

I assume it means it doesn't take any arguments.

**Comment by puredanger** [comment]
No, the difference that is trying to explain is that all of the other functions (like `map` transducer arity) _return_ a transducer function whereas `cat` itself _is_ a transducer function.
