### ISSUE TITLE
Expose visitors to very basic examples of Clojure code

### ISSUE THREAD

**Issue by kahunamoore** [clojure/clojure-site#56]
It seems that someone landing on the home page should be shown an example of Clojure code, even if it is only something as simple as '(println "Hello World"!)'

Giving the user a lot of text to read before seeing any code will increase the chance they will navigate away from the site.

If having front page code is not desirable then maybe just a side-bar (or side-bar link) to a page dedicated to basic code examples would help.

Clojure.org does have a Getting Started page but it is almost too minimal as well as too advanced. There is an example of launching the REPL (better off shown later?) and a math example. The Language sections on the getting started page talk about Comparators and Reader Conditionals, fairly advanced topics for the total newbie.

I'd suggest something like the following, possibly as examples in the REPL (e.g. with output):

## Hello world example

(println "Hello world")
=> Hello World

## Calling a built-in math function

(+ 1 1)
=> 2

## Defining an array

(def my-array [1 2 3])

## Printing my-array

etc...

## Defining a function

(defn add-two [x]
   (+ x 2))

## Calling your new add-two function

etc. etc.

If this is something the maintainers would like to see I can put something together with actual page of markdown, etc. to provide a starting point.

**Comment by arrdem** [comment]
Probable duplicate of #43, previously rejected/closed.

**Comment by kahunamoore** [comment]
Ah, ok my bad. I didn't search the Closed issues. Closing. However, the suggestions still hold for the Getting Started page. I'll look for an existing issue that addresses that page and make comments there as needed.
