### ISSUE TITLE
tools.build documentation - declare how to execute uberjar file

### ISSUE THREAD

**Issue by Dangercoder** [clojure/clojure-site#561]
The tools.build documentation could contain more information about how to produce uberjars and execute them.

- Different ways of building uberjars (the options)
-  How to produce an application uberjar that can be invoked by using java -jar

**Additional notes**
A good place to draw some inspiration is from this documentation: https://cljdoc.org/d/com.github.seancorfield/depstar/2.1.303/doc/getting-started/building-an-application-jar

**Comment by puredanger** [comment]
I've updated for the second bullet, not sure what you have in mind for the first. I believe the version documented in the guide is the best way to build uber jars with tools.build. Is there some other option you had in mind?

**Comment by puredanger** [comment]
Closing until something else requested...
