### ISSUE TITLE
Small suggestions for tools.build docs

### ISSUE THREAD

**Issue by phronmophobic** [clojure/clojure-site#573]
I'm finally getting around to trying `tools.build` and here are some of the small hurdles I ran into while trying to get up to speed with `tools.build`. If any of these suggestions sound interesting, I can follow the contrib process and submit a pull request. Tools.build has been working great. Thank you!

-----------

### 1. Add a "Getting Started" or "Installation" header before the second paragraph in the "Builds are programs" section.

For some reason, I assumed that `tools.build` was built into the clojure cli and didn't require any setup. I jumped straight to the Mixed Java/Clojure build section to follow that example.

Here's what I saw when I tried to run the example in terminal:

```sh
$ clj -T:build
No function found on command line or in :exec-fn
```

It's not that big a deal, but maybe it will streamline someone else's ramp up.

### 2. Provide link to latest or list of tool.build tags and shas

The example in "Builds are programs" provides this example for setting up the `:build` alias.
```clojure
{:paths ["src"]
 :deps {;; project deps
       }
 :aliases
 {:build {:deps {io.github.clojure/tools.build {:tag "TAG" :sha "SHA"}}
          :ns-default build}}}
```

It would be handy to either inline a reasonable TAG and SHA or include a link to somewhere like https://github.com/clojure/tools.build to make it easy to find a reasonable TAG and SHA.

### 3. Add relevant link to prep task section from "Mixed Java / Clojure build" section

The example says: "The compile task here can also be used as the prep task for this lib." It would be convenient to link to https://clojure.org/guides/deps_and_cli#prep_libs here.

### 4. Add example to "Mixed Java / Clojure build" section

Having an example to type in is helpful. Maybe something like:
```sh
clj -T:build compile :env :dev
```

**Comment by puredanger** [comment]
Thanks! Good suggestions.
