### ISSUE TITLE
news & guide pages should have a list rather than take you to first item

### ISSUE THREAD

**Issue by Martin-S-Weber** [clojure/clojure-site#58]
Go to http://clojure.org/news/2016/01/14/clojure-org-live and hit the 'news' link. You end up at  clojure.org/news/news which displays the 2016-01-14 article.

Same applies to the guides link -- linking to guides/ but displaying a guide instead of a listing of guides.

The events listing page DOES provide a listing of events.

expected is in all three cases a LISTING of ENTITY instead of you selecting a random entity for me.

**Comment by puredanger** [comment]
Both the news and guides page list the top page on the left nav, rather than repeating the left nav listing in the main body of the page.

**Comment by Martin-S-Weber** [comment]
I have seen the left nav. The lists on the left nav are indeed handy when you're looking at an entry!

Yet when I go to the server and ask for a listing, I'm looking at the main content area and expect a listing there, just like for the events page.

My personal expectancy would be that the listing page has all the links, whereas the left nav would only have the top x latest ones. In other words, I am seeing value in a listing page. I am also seeing value in consistency of interface, and thus would suggest choosing one way or another and be consistent about it (i.e., either fix the events page or both news & guides). My expectations (left nav not giving a proper full directory as it would grow too much vertically after a while) might be wrong though of course. (This is a subjective issue, I'm not a UX specialist to make this objective.)

**Comment by puredanger** [comment]
I'll leave this open and consider some options.

**Comment by puredanger** [comment]
Not going to change for now
