### ISSUE TITLE
Add some marketing to main page

### ISSUE THREAD

**Issue by ilevd** [clojure/clojure-site#601]
The main page has a description text and not much visual elements such as icons, colored blocks e.t.c. So I propose to remake it a little bit to make it more modern - for easiest pick up information and making first impression.

1. The main page doesn't have a description for which areas Clojure is intended (use cases).

I propose to add three blocks with a text such as:

- Web development
- Data analysys
- Administration/DevOps

Examples: 
https://go.dev/ - "What’s possible with Go" - 4 blocks (Cloud & Network Services, Command-line Interfaces ...  )
https://www.rust-lang.org/ - "Build it in Rust" - 4 blocks (Command Line, WebAssembly, ...)

2. Add a region with blocks with companies names and theirs logos - who uses Clojure, and a block "More" with a link to https://clojure.org/community/companies

**Comment by puredanger** [comment]
We have plans to overhaul the front page this year. I'm going to close this issue as I don't think it will help us in that (already started) effort, but appreciate the ideas!
