### ISSUE TITLE
Upcoming Clojure Events

### ISSUE THREAD

**Issue by openvest** [clojure/clojure-site#634]
I'm looking forward to [Clojure/Conj 2023](https://2023.clojure-conj.org/) (in person!)
It is missing from the [Clojure upcoming events](https://clojure.org/community/events)  which doesn't seem right.

**Comment by puredanger** [comment]
Sorry, I've been in the process of switching the event system to pull from the Clojure events calendar, but that's working now and the Conj is on there. Thanks!
