### ISSUE TITLE
Build docs for `clojure.core.server`

### ISSUE THREAD

**Issue by danielcompton** [clojure/clojure-site#64]
It looks like the API docs may not have been built for `clojure.core.server`? On the direct linking page, it links to the `clojure.repl-api` namespace which doesn't seem quite right.

> Additionally, there is a repl function provided that is slightly customized for use with the socket server in [clojure.core.server/repl](http://clojure.github.io/clojure/clojure.repl-api.html#clojure.core.server/repl).

**Comment by puredanger** [comment]
Yeah, looks like there might need to be something explicit updated in the doc generator - I will poke Tom about that.

I didn't see a bad link on the compilation page, but I did find a bad link on the repl_and_main page which I have fixed.

**Comment by puredanger** [comment]
Docs have been regenerated with the clojure.core.server ns. It's a little confusing though as only the top level namespaces show up on the left nav. Subnamespaces are included on the parent namespace page instead: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core.server
