### ISSUE TITLE
docs: explain cli tool -Tfoo and -T:foo are very different

### ISSUE THREAD

**Issue by sg-qwt** [clojure/clojure-site#657]
https://clojure.org/reference/deps_and_cli#tool_install

Clearly explain or notice people the difference between -T with and without colon, so that people don't get confused..

source: https://clojurians.slack.com/archives/C02B5GHQWP4/p1643109069018300?thread_ts=1643104858.017600&cid=C02B5GHQWP4

**Comment by puredanger** [comment]
Covered in the updated [Clojure CLI page](https://clojure.org/reference/clojure_cli#use_tool)
