### ISSUE TITLE
Broken url on news page

### ISSUE THREAD

**Issue by agilemaestro** [clojure/clojure-site#666]
Hello There,

On page https://clojure.org/news/news

There is a link on With Rich retiring from Nubank to
https://clojure.org/04/next-rich
instead of  
https://clojure.org/news/2023/08/04/next-rich

However,

it works fine from the actual address of https://clojure.org/news/news
which is https://clojure.org/news/2023/08/11/deref

**Comment by puredanger** [comment]
thanks, fixed
