### ISSUE TITLE
Add redirects from old site pages to new ones

### ISSUE THREAD

**Issue by danielcompton** [clojure/clojure-site#67]
A Google search for metadata takes me to http://clojure.org/Metadata, but it's new home is at /reference/metadata. It could be good to add redirects to the new page locations for the docs that existed before the new site.

**Comment by puredanger** [comment]
There are existing redirects in place for virtually all old pages (including http://clojure.org/metadata), however the site host is case sensitive for redirects (which I think is very weird but whatever). I already have installed all common capitalizations in the top 100 pages from the old site based on analytics (some like /Companies were very common). I decided that top 100 was where I'd draw the line.

We publish a sitemap and I've been trying to coax google into reindexing everything via the google tools, but it takes time. Eventually, this problem will disappear.

I'm not planning to add any more redirects.

**Comment by puredanger** [comment]
I added a /Metadata redirect along with a few others still in google.
