### ISSUE TITLE
clj documentation: how to see the resolved dependencies should be more findable

### ISSUE THREAD

**Issue by pbwolf** [clojure/clojure-site#675]
This is a suggestion that how to see a list or tree of resolved dependencies should be presented on page https://clojure.org/guides/deps_and_cli.  

Also, to put "how to see resolved dependencies" or a similarly relevant heading on https://clojure.org/reference/deps_and_cli, where `-X:deps tree` is currently under the heading "Other programs". I did not find it when I was looking for it.

**Comment by puredanger** [comment]
Updated both
