### ISSUE TITLE
clojure.org/Transducers 404's

### ISSUE THREAD

**Issue by ode79** [clojure/clojure-site#68]
This is the top link on Google for "clojure transducers".

If I search in the box on clojure.org I just get the same broken result.

**Comment by puredanger** [comment]
http://clojure.org/transducers (the old link) redirects appropriately but through the systems we're using redirects are case sensitive. There are a few like this in Google, no idea why. I installed redirects for the most common ones (top 100 urls) I saw in analytics. I was hoping to just wait google out on this, but maybe I should bite the bullet.

**Comment by puredanger** [comment]
Ok, I added redirects for /Metadata, /Sequences, /Transients, and /Transducers which all had this issue.
