### ISSUE TITLE
Robots file missing

### ISSUE THREAD

**Issue by danielcompton** [clojure/clojure-site#71]
It looks like www.clojure.org/robots.txt is 404'ing, and there used to be a sitemap for clojure.org which is also missing.

**Comment by puredanger** [comment]
http://clojure.org/sitemap.xml is there.

As this is a static site, we don't really have any pages to disallow for robots. Is there any reason to have a robots.txt?

**Comment by danielcompton** [comment]
Ah, missed the sitemap.

It's considered good practice to exclude search results like http://clojure.org/search?q=test from indexing. Also, you can link to the sitemap from your robots.txt file which saves you from submitting it to many different search engines - http://www.sitemaps.org/protocol.html#submit_robots
