### ISSUE TITLE
Add book entry for Numerical Linear Algebra for Programmers 2.0.0

### ISSUE THREAD

**Issue by blueberry** [clojure/clojure-site#711]
Book title: Numerical Linear Algebra for Programmers: An Interactive Tutorial with GPU, CUDA, OpenCL, MKL, Java and Clojure
URL: https://aiprobook.com/numerical-linear-algebra-for-programmers/
Publisher: Dragan Rocks
Publishing Date: 2024-12-20 (version 2.0.0, updated continuously)

(The code is 100% Clojure, even though it's not been given the spotlight in the title)

**Comment by puredanger** [comment]
added
