### ISSUE TITLE
Section for Video Courses

### ISSUE THREAD

**Issue by aadrian** [clojure/clojure-site#73]
Please improve the links to learning materials from "other" sources too :)

Another one important besides the existing books could be a "Video Courses" section. Just a few of existing video courses (in no particular order):
 - **Building Microservices with Clojure Training Video** - http://www.infiniteskills.com/training/building-microservices-with-clojure.html
 - **Learning ClojureScript Training Video** - http://www.infiniteskills.com/training/learning-clojurescript.html
 - **Learning Clojure Training Video** - http://www.infiniteskills.com/training/learning-clojure.html
 - **Up and Running with Clojure** - http://www.lynda.com/Clojure-tutorials/Up-Running-Clojure/413127-2.html
 - **Clojure Inside Out** - http://shop.oreilly.com/product/0636920030409.do
 - **Communicating Sequential Processes with core.async** - http://shop.oreilly.com/product/0636920041474.do
 - **Functional Thinking** - http://shop.oreilly.com/product/0636920030393.do
 - **Building Web Applications with Clojure** - https://www.packtpub.com/web-development/building-web-applications-clojure-video
 - **Clojure Concurrency** - https://www.pluralsight.com/courses/clojure-concurrency-tutorial
 - **Clojure Fundamentals - Part 1** - https://www.pluralsight.com/courses/clojure-fundamentals-part-one

Thank you.

**Comment by puredanger** [comment]
Will do, thanks.

**Comment by puredanger** [comment]
A lot of these were already on the resources page, but I added the rest.
