### ISSUE TITLE
A few more books!

### ISSUE THREAD

**Issue by aadrian** [clojure/clojure-site#74]
This list: https://www.reddit.com/r/Clojure/comments/3q9jaw/clojure_releases_vs_clojure_book_publication_dates/
seems to mention a few more books than the site http://clojure.org/community/books

Please extend the "official list" with the missing one, and also having the publication dates would be really helpful.

Thank you.

**Comment by puredanger** [comment]
Which are missing ?

The list is sorted in the order of newest release date.

**Comment by aadrian** [comment]
> Which are missing ?

Well, at least these (5 + 4) ones:
Released:
 - **Clojure Made Simple** - http://www.amazon.com/gp/product/B00BSY20HS
 - **ClojureScript: Up and Running** - http://www.amazon.com/ClojureScript-Up-Running-Stuart-Sierra/dp/1449327435
 - **Functional Programming Patterns in Scala and Clojure** - https://pragprog.com/book/mbfpp/functional-programming-patterns-in-scala-and-clojure
 - **Clojure for Domain-specific Languages** - http://www.amazon.com/gp/product/1782166505
 - **Mastering Clojure Data Analysis** - http://www.amazon.com/gp/product/1783284137

Also having Clojure specific chapters:
 - **Seven Concurrency Models in Seven Weeks** - https://pragprog.com/book/pb7con/seven-concurrency-models-in-seven-weeks
 - **Seven Languages in Seven Weeks** - https://pragprog.com/book/btlang/seven-languages-in-seven-weeks
 - **Seven More Languages in Seven Weeks** - https://pragprog.com/book/7lang/seven-more-languages-in-seven-weeks
 - **Seven Web Frameworks in Seven Weeks** - https://pragprog.com/book/7web/seven-web-frameworks-in-seven-weeks

Also upcoming, so one could list them too:
 - **Learning ClojureScript** - https://www.packtpub.com/web-development/learning-clojurescript
 - **Clojure for Java Developers** - https://www.packtpub.com/application-development/clojure-java-developers
 - **Mastering Clojure** - https://www.packtpub.com/application-development/mastering-clojure

**Comment by puredanger** [comment]
I added the first set of books and release dates. 

We're only including books primarily about Clojure, so the second set was not included.

We also only include books that have been released, so I have also skipped the last set.

**Comment by aadrian** [comment]
> We're only including books primarily about Clojure, so the second set was not included.

Maybe those could be mentioned in the "resources" section, or some WIKI page since the Chapters about Clojure(and frameworks) are also valuable for new users ?

Companies evaluating new adoption (e.g. Clojure) are greatly influenced by the abundance of available commercial materials: books and video training courses.

> We also only include books that have been released, so I have also skipped the last set.

Release date for the last set is February :).

**Comment by puredanger** [comment]
We have to draw the line somewhere, so I've drawn it where it is.

None of the last books are released yet. When they are, I will add them. It's common for books to be delayed (sometimes for years).

**Comment by aadrian** [comment]
New ClojureScript book https://leanpub.com/clojurescript-unraveled

**Comment by puredanger** [comment]
Added.
