### ISSUE TITLE
Misleading namespace link and thoughts regarding namespace nomenclature.

### ISSUE THREAD

**Issue by lgrapenthin** [clojure/clojure-site#76]
http://clojure.org/reference/reader

> 
'/' has special meaning, it can be used once in the middle of a symbol to separate the namespace from the name, e.g. my-namespace/foo. '/' by itself names the division function.

namespace here links to http://clojure.org/reference/namespaces which starts with "Namespaces are mappings from simple (unqualified) symbols to Vars and/or Classes."

This is not a good idea because the namespace of a symbol or keyword is not coupled to a "Clojure namespace".

- The link should be removed and a simple explanation should follow stating that a symbol can optionally have a namespace and this is mostly used to refer to Vars in "Clojure namespaces".

"Clojure namespaces" is just my idea how to solve the nomenclature clash. IMHO it (or a better alternative) should be applied consistently in the reference. It is based on the assumption that no one will stop calling Clojure namespaces "namespaces" in favor of a totally different name and the other assumption that somebody new to the language would get it wrong at least. 

The name "Clojure namespace" seems "correct" since "Clojure namespaces" serve the specific purpose of organizing code in a Clojure program while namespaces of symbols or keywords are general purpose namespaces in the literal sense of the word namespace. Think of "Clojure namespace" as the word namespace with the namespace "Clojure" :)

The paragraph about keywords mentions the `::` reader syntax and again suggests tight coupling to Clojure namespaces while it doesn't mention that  keywords can have any namespace which only adds to the at least incomplete impression.

- The `:window/rect` syntax should be explained before the `::` convencience

**Comment by puredanger** [comment]
* I removed the namespace link - I see your point and agree. I am not adding the additional sentence though - I don't think that needs to be explained here. Elsewhere, "libs" are used to describe Clojure namespaces, but that seems like a big concept with what most people think of as libraries.
* Re the `::` syntax, that actually *is* tightly coupled to namespaces as it uses the current namespace to do the resolution, so I'm leaving that.
* I added a line with a namespaced keyword prior to the `::` line
