### ISSUE TITLE
Use different colours for strings and comments

### ISSUE THREAD

**Issue by danielcompton** [clojure/clojure-site#79]
<img width="1377" alt="screenshot of google chrome 23-02-16 2-52-01 pm" src="https://cloud.githubusercontent.com/assets/811954/13239160/12cda4e0-da3d-11e5-8398-7f1f3baf45ac.png">

Strings and comments both have a very similar, if not the same colour. It could be good if they had different colours so they are more easily distinguished.

**Comment by puredanger** [comment]
The highlighter being used is highlight.js https://highlightjs.org/. It's highlighting tokens and comments and strings are both string tokens so this is what I would expect.

I don't know what capabilities are available in highlight.js to provide customized coloring per form but if you can [add that capability](https://github.com/isagalaev/highlight.js/blob/73ba066fe351d6a150c27e7dfcd17de1b535cd8d/src/languages/clojure.js), we can update.

**Comment by puredanger** [comment]
Strings are green and not italics, and comments are grey and italics. They seem pretty visually different to me and I don't think any action is needed.
