### ISSUE TITLE
Reader Conditionals guide

### ISSUE THREAD

**Issue by danielcompton** [clojure/clojure-site#8]
The page on the reader has a section on [Reader Conditionals](https://github.com/clojure/clojure-site/blob/0fdcbcc965b7b9a7f7670001a0f3a17ec57ff30f/content/reference/reader.adoc#reader-conditionals) and is written from the perspective of someone using the reader (as it should be). However it doesn't offer a lot of concrete advice or examples for how people can use Reader Conditionals in their code. Would you be open to a new page on Reader Conditionals? It could also briefly discuss prior art (e.g. cljx) so people new to Clojure can understand how Reader Conditionals fit and why they were created.

I've written http://danielcompton.net/2015/06/10/clojure-reader-conditionals-by-example and would be happy to adapt parts or all of it for this doc page.

**Comment by puredanger** [comment]
I would love to have a page under the "guide" section for this with your examples Daniel! We could then point to it from the reader page.
