### ISSUE TITLE
Link to specific (github) source for a given docs page, to enable easier pull-requests/issues

### ISSUE THREAD

**Issue by nilliams** [clojure/clojure-site#93]
This, thanks!

> alexmiller [11:07 PM] 
> @cnilliams: having a link from the site page to the github page is a good idea and very doable. If you file a GitHub issue on clojure-site to remind me, I'd be happy to add that

**Comment by lxsameer** [comment]
Does any one implemented this feature ?

**Comment by puredanger** [comment]
No, but I don't think it's possible to do without access to the templates, which are not part of the repo.

**Comment by puredanger** [comment]
Added in bottom right corner of footer
